/*
 * changePassword.java
 *
 * Created on March 31, 2014, 3:48 PM
 */

package hrms;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class changePassword extends javax.swing.JInternalFrame {
    String t;
    /** Creates new form changePassword */
    public changePassword(String ap) {
        initComponents();
        t=ap;
        System.out.println(t+"test");
        jTxtEmpId.setText(t);
    }
    private changePassword() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtEmpId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtCrrntPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jTxtNewPass = new javax.swing.JPasswordField();
        jBttnChngePass = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("CHANGE PASSWORD");

        jLabel2.setText("EMPLOYEE ID");

        jTxtEmpId.setEditable(false);
        jTxtEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmpIdActionPerformed(evt);
            }
        });
        jTxtEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtEmpIdKeyPressed(evt);
            }
        });

        jLabel3.setText("CURRENT PASSWORD");

        jTxtCrrntPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtCrrntPassKeyPressed(evt);
            }
        });

        jLabel4.setText("NEW PASSWORD");

        jTxtNewPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNewPassKeyPressed(evt);
            }
        });

        jBttnChngePass.setText("Change");
        jBttnChngePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnChngePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmpId, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jTxtNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jTxtCrrntPass, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jBttnChngePass)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCrrntPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jBttnChngePass)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnChngePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnChngePassActionPerformed
      String cp=jTxtCrrntPass.getText().trim();
      System.out.print(cp);
      String np=jTxtNewPass.getText().trim();
      System.out.print(np);
      if((jTxtCrrntPass.getText().equals(""))||(jTxtNewPass.getText().equals("")))
        {
            JOptionPane.showMessageDialog(rootPane,"You must enter values ");
        } 
      else {
      try
        {
               
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();      
            int committed = st.executeUpdate("update login set pass='"+np+"' where  uname='"+t+"'&& pass='"+cp+"'");
             if(committed>=1)
            {
                System.out.print("Executed");
                 JOptionPane.showMessageDialog(rootPane,"Password Changed"); 
            }else
            {
                System.out.print("No");
                JOptionPane.showMessageDialog(rootPane,"Wrong Password Entered"); 
                jTxtCrrntPass.setText("");
                jTxtNewPass.setText("");
            }
      }
        
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
      }
}//GEN-LAST:event_jBttnChngePassActionPerformed

    private void jTxtEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmpIdActionPerformed
        
    }//GEN-LAST:event_jTxtEmpIdActionPerformed

    private void jTxtEmpIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEmpIdKeyPressed
         
    }//GEN-LAST:event_jTxtEmpIdKeyPressed

    private void jTxtCrrntPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCrrntPassKeyPressed
        
    }//GEN-LAST:event_jTxtCrrntPassKeyPressed

    private void jTxtNewPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNewPassKeyPressed
        
    }//GEN-LAST:event_jTxtNewPassKeyPressed
public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changePassword().setVisible(true);
            }
        });
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnChngePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCrrntPass;
    private javax.swing.JTextField jTxtEmpId;
    private javax.swing.JTextField jTxtNewPass;
    // End of variables declaration//GEN-END:variables
    
}
