/*
 * DepartmentDetails.java
 *
 * Created on March 29, 2014, 11:41 AM
 */

package hrms;
import java.sql.*;

import javax.swing.JOptionPane;

        
/**
 *
 * @author  user1
 */
public class DepartmentDetails extends javax.swing.JInternalFrame {
    
    /** Creates new form DepartmentDetails */
    public DepartmentDetails() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCmbDcode = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jDepNam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCmbSecCod = new javax.swing.JComboBox();
        jSecNam = new javax.swing.JTextField();
        jbttnAdd = new javax.swing.JButton();
        jBttnEdit = new javax.swing.JButton();
        jbttnDelete = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("Departmant Details");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel2.setText("Department Code");

        jCmbDcode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCmbDcode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbDcodeItemStateChanged(evt);
            }
        });
        jCmbDcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbDcodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel3.setText("Department Name");

        jDepNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDepNamKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel4.setText("Section Code");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel5.setText("Section Name");

        jCmbSecCod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S1", "S2", "S3", "S4", "S5" }));
        jCmbSecCod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbSecCodItemStateChanged(evt);
            }
        });
        jCmbSecCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbSecCodActionPerformed(evt);
            }
        });

        jSecNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSecNamKeyPressed(evt);
            }
        });

        jbttnAdd.setText("Add");
        jbttnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnAddActionPerformed(evt);
            }
        });

        jBttnEdit.setText("Edit");
        jBttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnEditActionPerformed(evt);
            }
        });

        jbttnDelete.setText("Delete");
        jbttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbSecCod, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbDcode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSecNam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDepNam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jbttnAdd)
                        .addGap(63, 63, 63)
                        .addComponent(jBttnEdit)
                        .addGap(62, 62, 62)
                        .addComponent(jbttnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCmbDcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jDepNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCmbSecCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSecNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbttnAdd)
                    .addComponent(jBttnEdit)
                    .addComponent(jbttnDelete))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbttnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnAddActionPerformed
       try{
        int depCod = Integer.parseInt(jCmbDcode.getSelectedItem().toString());
        String depNam = jDepNam.getText().trim();
        String secCod = jCmbSecCod.getSelectedItem().toString().trim();
        String secNam = jSecNam.getText().trim();
        if((jDepNam.getText().equals(""))||(jSecNam.getText().equals(""))) 
             {       
               JOptionPane.showMessageDialog(rootPane,"You must enter values ");   
             }
        else
            {
        System.out.print(depCod);
        System.out.print(depNam);
        System.out.print(secCod);
        System.out.print(secNam);
        java.sql.Statement st = new Main().hrmsDatabase().createStatement();
        String sql="select dcode,dname from depdetails where dcode!=0";
        System.out.print(sql);
        ResultSet rs=st.executeQuery(sql);
        if(rs.next())
            {
            if(depCod==(Integer.parseInt(rs.getString(1)))){
             depNam = rs.getString(2);
             jDepNam.setText(depNam);
            }
        }
        int committed = st.executeUpdate("insert into depdetails(dcode,dname) values("+depCod+",'"+depNam+"')");
        committed = st.executeUpdate("insert into section(scode,depcode,sname) values('"+secCod+"',"+depCod+",'"+secNam+"')");
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
    }//GEN-LAST:event_jbttnAddActionPerformed
        }
        }
       catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
   }
        private void jBttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnEditActionPerformed
       int depCod = Integer.parseInt(jCmbDcode.getSelectedItem().toString());
       String depNam = jDepNam.getText().trim();
        String secCod = jCmbSecCod.getSelectedItem().toString().trim();
       String secNam = jSecNam.getText().trim();
       System.out.print(depCod);
       System.out.print(secCod);
       try
        {
      java.sql.Statement st = new Main().hrmsDatabase().createStatement();
        int committed = st.executeUpdate("update depdetails set dname='"+depNam+"',secname='"+secNam+"'where dcode="+depCod+"&&seccode='"+secCod+"'");
        if(committed>=1)
        {
            System.out.print("Executed");
           }
       else{
            System.out.print("No");
    }                                        
        JOptionPane.showMessageDialog(rootPane,"Edited");
      jCmbDcode.setSelectedItem("");
               jDepNam.setText("");
                jCmbSecCod.setSelectedItem("");
                jSecNam.setText("");
       }
    catch(Exception e)
       {
           System.out.print(e.getMessage());
           System.out.print("YYY");
          JOptionPane.showMessageDialog(rootPane,e.getMessage());
      }
   
}//GEN-LAST:event_jBttnEditActionPerformed

        private void jbttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnDeleteActionPerformed
String str1 = JOptionPane.showInputDialog(null, "Enter department code : ", "Department",1);
String str2 = JOptionPane.showInputDialog(null, "Enter section code : ", "Section",1);
if(str1 == null||str2==null)
	System.exit(0);
int dcode=Integer.parseInt(str1);   
String secCod=str2;
System.out.print(dcode);
System.out.print(secCod);
try
        {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            int committed1 = st.executeUpdate("delete from depdetails where dcode="+dcode+"&& seccode='"+secCod+"'");
           if(committed1>=1)
            {
                System.out.print("Executed");
            }else
            {
                System.out.print("No");
            }
           JOptionPane.showMessageDialog(rootPane,"Deleted");
         jCmbDcode.setSelectedItem("");
         jDepNam.setText("");
         jCmbSecCod.setSelectedItem("");
         jSecNam.setText("");
        }
        
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        
             
                          
        }//GEN-LAST:event_jbttnDeleteActionPerformed

        private void jCmbDcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbDcodeActionPerformed
      try{
      {            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from deptdetails where dcode='"+(String)jCmbDcode.getSelectedItem()+"'");
           if(rs.next())
            {
             jDepNam.setText(rs.getString("dname"));      
            }
            rs.close();
            st.close();
  }          
             java.sql.Statement st=new  Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from section where dcode='"+(String)jCmbDcode.getSelectedItem()+"'");
           if(rs.next())
            {
              jCmbSecCod.setSelectedItem(rs.getString("scode"));      
            }
            rs.close();
            st.close();
            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }        
}//GEN-LAST:event_jCmbDcodeActionPerformed

        private void jCmbSecCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbSecCodActionPerformed
          try{
             java.sql.Statement st=new  Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select sname from section where scode='"+(String)jCmbSecCod.getSelectedItem()+"'");
           if(rs.next())
            {
              jSecNam.setText(rs.getString("sname"));      
            }
            rs.close();
            st.close();

            
        } catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }   
        }//GEN-LAST:event_jCmbSecCodActionPerformed

        private void jCmbDcodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbDcodeItemStateChanged
           try{
      {            
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from depdetails where dcode='"+(String)jCmbDcode.getSelectedItem()+"'");
           if(rs.next())
            {
              jDepNam.setText(rs.getString("dname"));      
            }
            rs.close();
            st.close();
  }          
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from section where dcode='"+(String)jCmbDcode.getSelectedItem()+"'");
           if(rs.next())
            {
              jCmbSecCod.setSelectedItem(rs.getString("scode"));      
            }
            rs.close();
            st.close();
            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
        }//GEN-LAST:event_jCmbDcodeItemStateChanged

        private void jCmbSecCodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbSecCodItemStateChanged
           try{
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select sname from section where scode='"+(String)jCmbSecCod.getSelectedItem()+"'");
           if(rs.next())
            {
              jSecNam.setText(rs.getString("sname"));      
            }
            rs.close();
            st.close();
        } catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        } 
        }//GEN-LAST:event_jCmbSecCodItemStateChanged

        private void jDepNamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDepNamKeyPressed
         perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
         p1.dis(jDepNam, evt,num1);
        }//GEN-LAST:event_jDepNamKeyPressed

        private void jSecNamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSecNamKeyPressed
         perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
         p1.dis(jSecNam, evt,num1);   
        }//GEN-LAST:event_jSecNamKeyPressed
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnEdit;
    private javax.swing.JComboBox jCmbDcode;
    private javax.swing.JComboBox jCmbSecCod;
    private javax.swing.JTextField jDepNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jSecNam;
    private javax.swing.JButton jbttnAdd;
    private javax.swing.JButton jbttnDelete;
    // End of variables declaration//GEN-END:variables
    
}


