/*
 * DesignationDetails.java
 *
 * Created on March 29, 2014, 11:51 AM
 */

package hrms;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class DesignationDetails extends javax.swing.JInternalFrame {
    
    /** Creates new form DesignationDetails */
    public DesignationDetails() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComDesig = new javax.swing.JComboBox();
        jDesigNam = new javax.swing.JTextField();
        jPaySc = new javax.swing.JTextField();
        jComGrde = new javax.swing.JComboBox();
        jBttnAdd = new javax.swing.JButton();
        jBttnEdit = new javax.swing.JButton();
        jBttnSrch = new javax.swing.JButton();
        jBttnDlt = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("Designation Details");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel2.setText("Designation Code");

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel3.setText("Designation Name");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel4.setText("Pay Scale");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 14));
        jLabel5.setText("Grade");

        jComDesig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComDesig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComDesigItemStateChanged(evt);
            }
        });

        jDesigNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDesigNamKeyPressed(evt);
            }
        });

        jPaySc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPayScKeyPressed(evt);
            }
        });

        jComGrde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E" }));
        jComGrde.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComGrdeItemStateChanged(evt);
            }
        });

        jBttnAdd.setText("Add");
        jBttnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddActionPerformed(evt);
            }
        });

        jBttnEdit.setText("Edit");
        jBttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnEditActionPerformed(evt);
            }
        });

        jBttnSrch.setText("Search");
        jBttnSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSrchActionPerformed(evt);
            }
        });

        jBttnDlt.setText("Delete");
        jBttnDlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBttnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jBttnSrch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBttnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jBttnDlt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesigNam, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jComDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPaySc, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jComGrde, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComDesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDesigNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPaySc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComGrde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnDlt)
                    .addComponent(jBttnAdd)
                    .addComponent(jBttnEdit)
                    .addComponent(jBttnSrch))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddActionPerformed
         
        try{
        int desCod = Integer.parseInt(jComDesig.getSelectedItem().toString());
        String desNam = jDesigNam.getText().trim();
        String paySc = jPaySc.getText().trim();
        String grde = jComGrde.getSelectedItem().toString();
        if((jDesigNam.getText().equals(""))||(jPaySc.getText().equals("")))
        {
            JOptionPane.showMessageDialog(rootPane,"You must enter values ");
        } 
        else {
        System.out.print(desCod);
        System.out.print(desNam);
        System.out.print(paySc);
        System.out.print(grde);
        java.sql.Statement st = new Main().hrmsDatabase().createStatement();
        int committed = st.executeUpdate("insert into desdetails(descode,desname,pscale,grade) values("+desCod+",'"+desNam+"','"+paySc+"','"+grde+"')");
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
        }       
        }
        }
       catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
}//GEN-LAST:event_jBttnAddActionPerformed

    private void jBttnSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSrchActionPerformed
         String str = JOptionPane.showInputDialog(null, "Enter Designation Code : ", "HRMS",1);
        if(str==null)
		System.exit(0);
        int desCod=Integer.parseInt(str); 
        System.out.print(desCod);
        try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from desdetails where descode="+desCod+"";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
            {
                System.out.print("Executed");
                jComDesig.setSelectedItem(rs.getString(1));
                jDesigNam.setText(rs.getString(2));
                jPaySc.setText(rs.getString(3));
                jComGrde.setSelectedItem(rs.getString(4));
             }else
              {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
  
}//GEN-LAST:event_jBttnSrchActionPerformed

    private void jBttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnEditActionPerformed
       try {
        int desCod = Integer.parseInt(jComDesig.getSelectedItem().toString());
       String desNam = jDesigNam.getText().trim();
        String paySc = jPaySc.getText().trim();
       String grde = jComGrde.getSelectedItem().toString();
       System.out.print(desCod);
      java.sql.Statement st = new Main().hrmsDatabase().createStatement();
        int committed = st.executeUpdate("update desdetails set desname='"+desNam+"',pscale='"+paySc+"',desname='"+grde+"'where descode="+desCod+"");
        if(committed>=1)
        {
            System.out.print("Executed");
           }
       else{
            System.out.print("No");
    }                                        
        JOptionPane.showMessageDialog(rootPane,"Edited");
      jComDesig.setSelectedItem("");
      jDesigNam.setText("");
      jPaySc.setText("");
      jComGrde.setSelectedItem("");
       }
    catch(Exception e)
       {
           System.out.print(e.getMessage());
           System.out.print("YYY");
          JOptionPane.showMessageDialog(rootPane,e.getMessage());
      }
    }//GEN-LAST:event_jBttnEditActionPerformed

    private void jBttnDltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDltActionPerformed
       String str = JOptionPane.showInputDialog(null, "Enter designation code : ", "Designation",1);
if(str == null)
	System.exit(0);
int desCod=Integer.parseInt(str);   
System.out.print(desCod);
try
        {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            int committed1 = st.executeUpdate("delete from desdetails where descode="+desCod+"");
           if(committed1>=1)
            {
                System.out.print("Executed");
            }else
            {
                System.out.print("No");
            }
           JOptionPane.showMessageDialog(rootPane,"Deleted");
         jComDesig.setSelectedItem("");
         jDesigNam.setText("");
         jPaySc.setText("");
         jComGrde.setSelectedItem("");
        }
        
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
}//GEN-LAST:event_jBttnDltActionPerformed

    private void jComDesigItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComDesigItemStateChanged
         try
    {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select desname from desdetails where descode='"+(String)jComDesig.getSelectedItem()+"'");
           if(rs.next())
            {
              jDesigNam.setText(rs.getString("desname"));      
            }
            rs.close();
            st.close();

            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
    }//GEN-LAST:event_jComDesigItemStateChanged

    private void jComGrdeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComGrdeItemStateChanged
        try
    {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select grade from desdetails where grade='"+(String)jComGrde.getSelectedItem()+"'");
           if(rs.next())
            {
              jDesigNam.setText(rs.getString("dsname"));      
            }
            rs.close();
            st.close();

            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
    }//GEN-LAST:event_jComGrdeItemStateChanged

    private void jDesigNamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDesigNamKeyPressed
         perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
         p1.dis(jDesigNam, evt,num1);
    }//GEN-LAST:event_jDesigNamKeyPressed

    private void jPayScKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPayScKeyPressed
        perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
         p1.dis(jPaySc, evt,num2);
    }//GEN-LAST:event_jPayScKeyPressed
     public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignationDetails().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAdd;
    private javax.swing.JButton jBttnDlt;
    private javax.swing.JButton jBttnEdit;
    private javax.swing.JButton jBttnSrch;
    private javax.swing.JComboBox jComDesig;
    private javax.swing.JComboBox jComGrde;
    private javax.swing.JTextField jDesigNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jPaySc;
    // End of variables declaration//GEN-END:variables
    
}
