/*
 * empFamily.java
 *
 * Created on April 1, 2014, 11:21 AM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class empFamily extends javax.swing.JInternalFrame {
    
    /** Creates new form empFamily */
    public empFamily() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jnam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jrnam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jRmal = new javax.swing.JRadioButton();
        jRfmale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jdob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRsin = new javax.swing.JRadioButton();
        jRmar = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jocu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JRy = new javax.swing.JRadioButton();
        JRn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jrelatn = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("FAMILY DETAILS");

        jLabel2.setText("EMPLOYEE ID");

        jid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jidKeyPressed(evt);
            }
        });

        jLabel3.setText("EMPLOYEE NAME");

        jnam.setEditable(false);
        jnam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jnamKeyPressed(evt);
            }
        });

        jLabel4.setText("RELATIVE NAME");

        jrnam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrnamKeyPressed(evt);
            }
        });

        jLabel5.setText("GENDER");

        buttonGroup1.add(jRmal);
        jRmal.setText("MALE");

        buttonGroup1.add(jRfmale);
        jRfmale.setText("FEMALE");

        jLabel6.setText("DATE OF BIRTH");

        jdob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdobKeyPressed(evt);
            }
        });

        jLabel7.setText("MARITAL STATUS");

        buttonGroup2.add(jRsin);
        jRsin.setText("SINGLE");

        buttonGroup2.add(jRmar);
        jRmar.setText("MARRIED");

        jLabel8.setText("OCCUPATION");

        jocu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jocuKeyPressed(evt);
            }
        });

        jLabel9.setText("DEPENDENT");

        buttonGroup3.add(JRy);
        JRy.setText("YES");

        buttonGroup3.add(JRn);
        JRn.setText("NO");

        jLabel10.setText("RELATION");

        jrelatn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrelatnKeyPressed(evt);
            }
        });

        ADD.setText("Add");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        EDIT.setText("Edit");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        SEARCH.setText("Search");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel10))))
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ADD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SEARCH)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRmal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRfmale))
                    .addComponent(jrnam)
                    .addComponent(jrelatn)
                    .addComponent(jid)
                    .addComponent(jnam)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JRy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JRn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRsin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRmar))
                            .addComponent(jocu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EDIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DELETE))
                    .addComponent(jdob))
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jnam, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jrnam, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRmal)
                    .addComponent(jRfmale))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jdob, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRsin)
                    .addComponent(jRmar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JRy)
                        .addComponent(JRn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jrelatn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADD)
                    .addComponent(EDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DELETE)
                    .addComponent(SEARCH))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
          String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
         if(str==null)
		System.exit(0);
         String empid = str;
         System.out.print(empid);
        try
        {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            int committed1 = st.executeUpdate("delete from famdetails where empid='"+empid+"'");
           if(committed1>=1)
            {
                System.out.print("Executed");
            }else
            {
                System.out.print("No");
            }
           JOptionPane.showMessageDialog(rootPane,"Deleted");
        
        }
        
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
         jid.setText("");
         jnam.setText("");
         jrnam.setText("");
         jRmal.setSelected(false);
         jdob.setText("");
         jRsin.setSelected(false);
         jocu.setText("");
         JRy.setSelected(false);
         jrelatn.setText("");
}//GEN-LAST:event_DELETEActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
       try{
           String emid = jid.getText().trim();
           String emnam = jnam.getText().trim();
           String relnam = jrnam.getText().trim();
             String gend=null;
            if (jRmal.isSelected()) {
                gend = "Male";
            }
            if (jRfmale.isSelected()) {
                gend = "Female";
            }
           String dob = jdob.getText().trim();
             String marst=null;
            if (jRsin.isSelected()) {
                marst = "single";
            }
            if (jRmar.isSelected()) {
               marst= "married";
            }
           String occup = jocu.getText().trim();
             String depn=null;
            if (JRy.isSelected()) {
                depn = "yes";
            }
            if (JRn.isSelected()) {
                depn = "no";
            }
        if((jid.getText().equals(""))||(jnam.getText().equals(""))||(jrnam.getText().equals(""))||(jdob.getText().equals(""))||(jocu.getText().equals(""))||(jrelatn.getText().equals("")))
        {
             JOptionPane.showMessageDialog(rootPane,"You must enter values ");
        }
        else {
        String rela = jrelatn.getText().trim();
        System.out.print(emid);
        System.out.print(emnam);
        System.out.print(relnam);
        System.out.print(gend);
        System.out.print(dob);
        System.out.print(marst);
        System.out.print(occup);
        System.out.print(depn);
        System.out.print(rela); 
         java.sql.Statement st = new Main().hrmsDatabase().createStatement();
     int committed = st.executeUpdate("insert into famdetails(empid,empname,relname,gender,dob,marstatus,occu,depen,relation) values('"+emid+"','"+emnam+"','"+relnam+"','"+gend+"','"+dob+"','"+marst+"','"+occup+"','"+depn+"','"+rela+"')");   
     if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
            }
      }
     }
       catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }                                          
            
}//GEN-LAST:event_ADDActionPerformed

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
         try{
          String emid = jid.getText().trim();
           jid.disable();
           String emnam = jnam.getText().trim();
           jnam.disable();
           String relnam = jrnam.getText().trim();
             String gend=null;
            if (jRmal.isSelected()) {
                gend = "Male";
            }
            if (jRfmale.isSelected()) {
                gend = "Female";
            }
           String dob = jdob.getText().trim();
             String marst=null;
            if (jRsin.isSelected()) {
                marst = "single";
            }
            if (jRmar.isSelected()) {
               marst= "married";
            }
           String occup = jocu.getText().trim();
             String depn=null;
            if (JRy.isSelected()) {
                depn = "yes";
            }
            if (JRn.isSelected()) {
                depn = "no";
            }
           String rela = jrelatn.getText().trim();
            System.out.print(jid);
            System.out.print(emnam);
            System.out.print(relnam);
            System.out.print(gend);
            System.out.print(dob);
            System.out.print(marst);
            System.out.print(occup);
            System.out.print(depn);
            System.out.print(rela);
         java.sql.Statement st = new Main().hrmsDatabase().createStatement();
     int committed = st.executeUpdate("update famdetails set relname = '"+relnam+"',gender = '"+gend+"',dob = '"+dob+"',marstatus = '"+marst+"',occu = '"+occup+"',depen = '"+depn+"',relation = '"+rela+"' where empid = '"+emid+"'");
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else
        {
         System.out.print("NO");
        }
            
       }
       catch(Exception e)
       {
           System.out.print(e.getMessage());
           System.out.print("yyy");
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       
   }
    }//GEN-LAST:event_EDITActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
       String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String empid = str;
         System.out.print(empid);
        try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from famdetails where empid='"+empid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
            {
                System.out.print("Executed");
                jid.setText(rs.getString(1));
                jid.disable();
                jnam.setText(rs.getString(2));
                jnam.disable();
                jrnam.setText(rs.getString(3));
                if (rs.getString(4)== "Male") {
                    jRmal.doClick();
                }
                else {
                    jRfmale.doClick();
                }
                jdob.setText(rs.getString(5));
                if (rs.getString(6) == "single") {
                    jRsin.doClick();
                }
                else {
                    jRmar.doClick();
                }
                jocu.setText(rs.getString(7));
                if(rs.getString(8) == "yes") {
                    JRy.doClick();
                }
                else {
                    JRn.doClick();
                }
                jrelatn.setText(rs.getString(9));
                }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }  
    }//GEN-LAST:event_SEARCHActionPerformed

    private void jnamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnamKeyPressed
      perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jnam, evt,num1);
    
    }//GEN-LAST:event_jnamKeyPressed

    private void jrnamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrnamKeyPressed
     perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jrnam, evt,num1);
    
    }//GEN-LAST:event_jrnamKeyPressed

    private void jdobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdobKeyPressed
        if (evt.getKeyChar()==evt.VK_ENTER)
         {
              String str=jdob.getText();
             String sub=jdob.getText().substring(0,4).toString();
             JOptionPane.showMessageDialog(null,sub);
              if(isValidDate(str))
        { 
                  //    System.out.println("valid");    
                
              
           }   
           else  
           {  
               JOptionPane.showMessageDialog(null,"Invalid Date");
               jdob.setText("");
           }   
         }
         
    }//GEN-LAST:event_jdobKeyPressed

    private void jocuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jocuKeyPressed
       perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jocu, evt,num1);
    }//GEN-LAST:event_jocuKeyPressed

    private void jrelatnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrelatnKeyPressed
        perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jrelatn, evt,num1);
        
    }//GEN-LAST:event_jrelatnKeyPressed

    private void jidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jidKeyPressed
         perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jid, evt,num2);
        if (evt.getKeyChar()==evt.VK_ENTER){
            try {
            int emid = Integer.parseInt(jid.getText());
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select fname from empdetails where empid = " + emid + "");
            if(rs.next())
            {
             jnam.setText(rs.getString("fname"));
            }
            rs.close();
            st.close();
            
        } catch (SQLException ex) {                             
            Logger.getLogger(expDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    }//GEN-LAST:event_jidKeyPressed
    public static boolean  isValidDate(String date){  
             String expression = "((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])";
          String dateFormat = "yyyy-MM-dd";
          CharSequence inputStr = date;  
          Pattern pattern = Pattern.compile(expression,Pattern.CASE_INSENSITIVE);  
          Matcher matcher = pattern.matcher(inputStr);  
          if(matcher.matches()){
          SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
		sdf.setLenient(false);
        	try {
 
			//if not valid, it will throw ParseException
			Date dateValidated = sdf.parse(date);
			System.out.println(dateValidated);
                        return true;
		}
          catch (ParseException e) {
 			e.printStackTrace();
			return false;
		}
          }
          else{
              return false;
          }
      } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton DELETE;
    private javax.swing.JButton EDIT;
    private javax.swing.JRadioButton JRn;
    private javax.swing.JRadioButton JRy;
    private javax.swing.JButton SEARCH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRfmale;
    private javax.swing.JRadioButton jRmal;
    private javax.swing.JRadioButton jRmar;
    private javax.swing.JRadioButton jRsin;
    private javax.swing.JTextField jdob;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField jnam;
    private javax.swing.JTextField jocu;
    private javax.swing.JTextField jrelatn;
    private javax.swing.JTextField jrnam;
    // End of variables declaration//GEN-END:variables
    
}
