/*
 * empPlacement.java
 *
 * Created on March 31, 2014, 3:09 PM
 */
package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class empPlacement extends javax.swing.JInternalFrame {

    int y, ano;

    /** Creates new form empPlacement */
    public empPlacement() {
        initComponents();
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int mon = month + 1;
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        System.out.println("Current date : " + day + "/" + (month + 1) + "/" + year);
        String dat = year + "-" + mon + "-" + day;
        jtdoj.setText(dat);
        try {
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select max(empid) from empdetails");
            if (rs.next()) {
                ano = rs.getInt(1) + 1;
            }
            jTxtPlce.setText(String.valueOf(ano));
            rs.close();
            st.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("yyy");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jteid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtst = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtlo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtsid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCombcom = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jtcu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtdoj = new javax.swing.JTextField();
        ADD = new javax.swing.JButton();
        EDIT = new javax.swing.JButton();
        SRCH = new javax.swing.JButton();
        DLTE = new javax.swing.JButton();
        jCombdc = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTxtPlce = new javax.swing.JTextField();
        jDepNam = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("PLACEMENT DETAILS");

        jLabel2.setText("EMPLOYEE ID");

        jteid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jteidKeyPressed(evt);
            }
        });

        jLabel3.setText("STATUS");

        jtst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtstKeyPressed(evt);
            }
        });

        jLabel4.setText("DEPARTMENT CODE");

        jLabel5.setText("LOCATION");

        jtlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtloKeyPressed(evt);
            }
        });

        jLabel6.setText("SUPERVISOR ID");

        jtsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtsidKeyPressed(evt);
            }
        });

        jLabel7.setText("COMPANY");

        jCombcom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INFOSYS", "IBM", "WIPRO", "SATYAM", "TTS" }));

        jLabel8.setText("CONTRIBUTION UNIT");

        jtcu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtcuKeyPressed(evt);
            }
        });

        jLabel9.setText("DATE OF JOINING");

        jtdoj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtdojKeyPressed(evt);
            }
        });

        ADD.setText("Add");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });

        EDIT.setText("Edit");
        EDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITActionPerformed(evt);
            }
        });

        SRCH.setText("Search");
        SRCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRCHActionPerformed(evt);
            }
        });

        DLTE.setText("Delete");
        DLTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DLTEActionPerformed(evt);
            }
        });

        jCombdc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCombdc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombdcItemStateChanged(evt);
            }
        });
        jCombdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombdcActionPerformed(evt);
            }
        });

        jLabel10.setText("PLACEMENT ID");

        jTxtPlce.setEditable(false);

        jDepNam.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtst)
                    .addComponent(jteid)
                    .addComponent(jtlo)
                    .addComponent(jtsid)
                    .addComponent(jCombcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtcu)
                    .addComponent(jtdoj)
                    .addComponent(jTxtPlce, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCombdc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDepNam)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(ADD)
                .addGap(33, 33, 33)
                .addComponent(SRCH)
                .addGap(60, 60, 60)
                .addComponent(EDIT)
                .addGap(29, 29, 29)
                .addComponent(DLTE)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPlce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDepNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCombcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtcu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtdoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DLTE)
                    .addComponent(EDIT)
                    .addComponent(SRCH)
                    .addComponent(ADD))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed
        try {
            String placeid = jTxtPlce.getText().trim();
            String emid = jteid.getText().trim();
            String stts = jtst.getText().trim();
            String dptcd = (String) jCombdc.getSelectedItem();
            String lctn = jtlo.getText().trim();
            String sprid = jtsid.getText().trim();
            String cmpny = (String) jCombcom.getSelectedItem();
            String cntrunit = jtcu.getText().trim();
            String doj = jtdoj.getText().trim();
            if(jteid.getText().equals("")||jtst.getText().equals("")||jtlo.getText().equals("")||jtsid.getText().equals("")||
            jtcu.getText().equals("")||jtdoj.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane,"You must enter values ");    
            }
            else {
            System.out.print(emid);
            System.out.print(stts);
            System.out.print(dptcd);
            System.out.print(lctn);
            System.out.print(sprid);
            System.out.print(cmpny);
            System.out.print(cntrunit);
            System.out.print(doj);
             boolean isExist = isValidEmp(emid);
        if(isExist){
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("insert into placedetails(placeid,empid,status,depcode,loca,sid,com,ctrlunit,doj) values('" + placeid + "','" + emid + "','" + stts + "','" + dptcd + "','" + lctn + "','" + sprid + "','" + cmpny + "','" + cntrunit + "','" + doj + "')");/*                            
            int committed = st.executeUpdate("insert into placedetails(empid,status,depcode,loca,sid,com,ctrlunit,doj) values('" + emid + "','" + stts + "','" + dptcd + "','" + lctn + "','" + sprid + "','" + cmpny + "','" + cntrunit + "','" + doj + "')");//GEN-LAST:event_ADDActionPerformed
           */ if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Invalid Entry");
        }
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       } 
    }

    private void EDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITActionPerformed
        try {
            jTxtPlce.disable();
            jteid.disable();
            String emid = jteid.getText().trim();
            String stts = jtst.getText().trim();
            String dptcd = (String) jCombdc.getSelectedItem();
            String lctn = jtlo.getText().trim();
            String sprid = jtsid.getText().trim();
            String cmpny = (String) jCombcom.getSelectedItem();
            String cntrunit = jtcu.getText().trim();
            String doj = jtdoj.getText().trim();
            System.out.print(emid);
            System.out.print(stts);
            System.out.print(dptcd);
            System.out.print(lctn);
            System.out.print(sprid);
            System.out.print(cmpny);
            System.out.print(cntrunit);
            System.out.print(doj);
             boolean isExist = isValidEmp(emid);
        if(isExist){
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("update placedetails set status = '" + stts + "',depcode = '" + dptcd + "',loca = '" + lctn + "',sid = '" + sprid + "',com = '" + cmpny + "',ctrlunit = '" + cntrunit + "',doj = '" + doj + "'"); 
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else{
            System.out.print("No");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Invalid Entry");
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       } 
    }//GEN-LAST:event_EDITActionPerformed

    private void SRCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRCHActionPerformed
        String str = JOptionPane.showInputDialog(null, "Enter Placement ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String placeid = str;
         System.out.print(placeid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from placedetails where placeid='"+placeid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jTxtPlce.setText(rs.getString(1));
                jteid.setText(rs.getString(2));
                jteid.disable();
                jtst.setText(rs.getString(3));
                jCombdc.setSelectedItem(rs.getString(4));
                jtlo.setText(rs.getString(5));
                jtsid.setText(rs.getString(6));
                jCombcom.setSelectedItem(rs.getString(7));
                jtcu.setText(rs.getString(8));
                jtdoj.setText(rs.getString(9));
                }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_SRCHActionPerformed

    private void DLTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DLTEActionPerformed
        try {
            String str = JOptionPane.showInputDialog(null, "Enter Placement ID : ", "HRMS", 1);
            if (str == null) {
                System.exit(0);
            }
            String plid = str;
            System.out.print(plid);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("delete from placedetails where placeid='" + plid + "'");
            if(committed>=1)
            {
                System.out.print("Executed");
            }else
            {
                System.out.print("No");
            }
           JOptionPane.showMessageDialog(rootPane,"Deleted");
            jteid.setText("");
            jtst.setText("");
            jCombdc.setSelectedItem(1);
            jtlo.setText("");
            jtsid.setText("");
            jCombcom.setSelectedItem(1);
            jtcu.setText("");//GEN-LAST:event_DLTEActionPerformed
            jtdoj.setText("");
        }
         catch (SQLException ex) {
            Logger.getLogger(empPlacement.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
            private void jCombdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombdcActionPerformed
                // TODO add your handling code here:
            }//GEN-LAST:event_jCombdcActionPerformed

            private void jteidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jteidKeyPressed
                 perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jteid, evt,num2);
            }//GEN-LAST:event_jteidKeyPressed

            private void jtstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtstKeyPressed
                 perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jtst, evt,num1);
            }//GEN-LAST:event_jtstKeyPressed

            private void jtloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtloKeyPressed
                perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jtlo, evt,num1);
            }//GEN-LAST:event_jtloKeyPressed

            private void jtsidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtsidKeyPressed
                perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jtsid, evt,num3);
            }//GEN-LAST:event_jtsidKeyPressed

            private void jtcuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcuKeyPressed
                perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jtcu, evt,num1);
            }//GEN-LAST:event_jtcuKeyPressed

            private void jtdojKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtdojKeyPressed
                 if (evt.getKeyChar()==evt.VK_ENTER)
         {
              String str=jtdoj.getText();
              if(isValidDate(str))
        { 
                  //    System.out.println("valid");    
            }   
           else  
           {  
               JOptionPane.showMessageDialog(null,"Invalid Date");
               jtdoj.setText("");
           }   
         } 
            }//GEN-LAST:event_jtdojKeyPressed

            private void jCombdcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombdcItemStateChanged
                try{
                  
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from depdetails where dcode='"+(String)jCombdc.getSelectedItem()+"'");
           if(rs.next())
            {
              jDepNam.setText(rs.getString("dname"));      
            }
            rs.close();
            st.close();                  
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
            }//GEN-LAST:event_jCombdcItemStateChanged
   public static boolean  isValidDate(String date){  
             String expression = "((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])";
          String dateFormat = "yyyy-MM-dd";
          CharSequence inputStr = date;  
          Pattern pattern = Pattern.compile(expression,Pattern.CASE_INSENSITIVE);  
          Matcher matcher = pattern.matcher(inputStr);  
          if(matcher.matches()){
          SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
		sdf.setLenient(false);
        	try {
 
			//if not valid, it will throw ParseException
			Date dateValidated = sdf.parse(date);
			System.out.println(dateValidated);
                        return true;
		}
          catch (ParseException e) {
 			e.printStackTrace();
			return false;
		}
          }
          else{
              return false;
          }
      } 
   public static boolean  isValidEmp(String empId) throws SQLException{  
            boolean isExist = false; 
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql= "select * from empdetails where empid='"+empId+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                isExist = true;
            }
            return isExist;  
      }     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JButton DLTE;
    private javax.swing.JButton EDIT;
    private javax.swing.JButton SRCH;
    private javax.swing.JComboBox jCombcom;
    private javax.swing.JComboBox jCombdc;
    private javax.swing.JTextField jDepNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTxtPlce;
    private javax.swing.JTextField jtcu;
    private javax.swing.JTextField jtdoj;
    private javax.swing.JTextField jteid;
    private javax.swing.JTextField jtlo;
    private javax.swing.JTextField jtsid;
    private javax.swing.JTextField jtst;
    // End of variables declaration//GEN-END:variables
    
}
