/*
 * empQualification.java
 *
 * Created on April 2, 2014, 2:13 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class empQualification extends javax.swing.JInternalFrame {
    
    /** Creates new form empQualification */
    public empQualification() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jEmpid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCombqual = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jBdUnvst = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jInst = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpArea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPercnt = new javax.swing.JTextField();
        jBttnAdd = new javax.swing.JButton();
        jBttnEdit = new javax.swing.JButton();
        jBttnSrch = new javax.swing.JButton();
        jBttnDlte = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("QUALIFICATION DETAILS");

        jLabel2.setText("EMPLOYEE ID");

        jEmpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpidActionPerformed(evt);
            }
        });
        jEmpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmpidKeyPressed(evt);
            }
        });

        jLabel3.setText("QUALIFICATION");

        jCombqual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BSC", "BTECH", "MSC", "MCOM" }));

        jLabel4.setText("BOARD/UNIVERSITY");

        jBdUnvst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBdUnvstKeyPressed(evt);
            }
        });

        jLabel5.setText("INSTITUTION");

        jInst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jInstKeyPressed(evt);
            }
        });

        jPs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPsKeyPressed(evt);
            }
        });

        jLabel7.setText("PERIOD OF STUDY");

        jLabel8.setText("SPECIALISED AREA");

        jSpArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpAreaKeyPressed(evt);
            }
        });

        jLabel9.setText("PERCENTAGE");

        jPercnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPercntKeyPressed(evt);
            }
        });

        jBttnAdd.setText("Add");
        jBttnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddActionPerformed(evt);
            }
        });

        jBttnEdit.setText("Edit");
        jBttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnEditActionPerformed(evt);
            }
        });

        jBttnSrch.setText("Search");
        jBttnSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSrchActionPerformed(evt);
            }
        });

        jBttnDlte.setText("Delete");
        jBttnDlte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDlteActionPerformed(evt);
            }
        });

        jLabel10.setText("(yyyy-yyyy)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBttnAdd)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jBttnSrch)
                                        .addGap(34, 34, 34)
                                        .addComponent(jBttnEdit)
                                        .addGap(36, 36, 36)
                                        .addComponent(jBttnDlte))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jPercnt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCombqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPs, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jInst, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(jBdUnvst, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jEmpid, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jSpArea, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCombqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBdUnvst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jSpArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPercnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnDlte)
                    .addComponent(jBttnEdit)
                    .addComponent(jBttnAdd)
                    .addComponent(jBttnSrch))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddActionPerformed
           try{
            String emid = jEmpid.getText().trim();
            String qual = (String) jCombqual.getSelectedItem();
            String stdy = jBdUnvst.getText().trim();
            String inst = jInst.getText().trim();
            String prdstudy = jPs.getText().trim();
            String spArea = jSpArea.getText().trim();
            String prcntge = jPercnt.getText().trim();
            if(jEmpid.getText().equals("")||jBdUnvst.getText().equals("")||jInst.getText().equals("")||jPs.getText().equals("")||jSpArea.getText().equals("")||jPercnt.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane,"You must enter values ");
            }
            else {
          boolean isExist = isValidEmp(emid);
          if(isExist){
              //String expression = "((19?[7[9]|[89][0-9]])|(20?0?[0-9]|1?[0-4]))-((19?[7[9]|[89][0-9]])|(20?0?[0-9]|1?[0-4]))";
          //CharSequence inputStr = prdstudy;  
          //Pattern pattern = Pattern.compile(expression,Pattern.CASE_INSENSITIVE);  
          //Matcher matcher = pattern.matcher(inputStr);
               if(prdstudy.matches("....-....")) {  
                   int sub1=Integer.parseInt(prdstudy.substring(0,4).toString());
               System.out.println("Check!");
              int sub2=Integer.parseInt(prdstudy.substring(5,4).toString());
               System.out.println("Check!");
              int dateMin = GregorianCalendar.YEAR-18;
              int dateMax = GregorianCalendar.YEAR-1;
                   if((sub1<sub2)&&(sub1>=dateMin&&sub1<=dateMax)&&(sub2>=dateMin&&sub2<=dateMax)){
                   java.sql.Statement st = new Main().hrmsDatabase().createStatement();
               int committed = st.executeUpdate("insert into qualdetails(empid,qual,boun,inst,perstudy,specarea,percent) values('" + emid + "','" + qual + "','" + stdy + "','" + inst + "','" + prdstudy + "','" + spArea + "','" + prcntge + "')");                                   
               if(committed>=1)
                     {
                        System.out.print("Executed");
                        JOptionPane.showMessageDialog(rootPane,"Saved!");
                     }
                 else{
                         System.out.print("No");
                     }
                   }
                   else{
                       JOptionPane.showMessageDialog(rootPane,"Invalid Period of study!");
                   }
              }
        else{
             JOptionPane.showMessageDialog(rootPane,"Invalid Period of study!");
         }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Employee Does Not Exist!");
        }
            }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
}//GEN-LAST:event_jBttnAddActionPerformed

    private void jBttnSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSrchActionPerformed
       String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String empid = str;
         System.out.print(empid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from qualdetails where empid='"+empid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jEmpid.setText(rs.getString(1));
                jEmpid.disable();
                jCombqual.setSelectedItem(rs.getString(2));
                jBdUnvst.setText(rs.getString(3));
                jInst.setText(rs.getString(4));
                jPs.setText(rs.getString(5));
                jSpArea.setText(rs.getString(6));
               jPercnt.setText(rs.getString(7));
                }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }          
    }//GEN-LAST:event_jBttnSrchActionPerformed

    private void jBttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnEditActionPerformed
        try{
            jEmpid.disable();
            String emid = jEmpid.getText().trim();
            String qual = (String) jCombqual.getSelectedItem();
            String stdy = jBdUnvst.getText().trim();
            String inst = jInst.getText().trim();
            String prdstudy = jPs.getText().trim();
            String spArea = jSpArea.getText().trim();
            String prcntge = jPercnt.getText().trim();
            System.out.print(emid);
            System.out.print(qual);
            System.out.print(stdy);
            System.out.print(inst);
            System.out.print(prdstudy);
            System.out.print(spArea);
            System.out.print(prcntge);
             boolean isExist = isValidEmp(emid);
        if(isExist){
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("update qualdetails set qual = '" + qual + "',boun = '" + stdy + "',inst = '" + inst + "',perstudy = '" + prdstudy + "',specarea = '" + spArea + "',percent = '" + prcntge + "'");                                   
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else{
            System.out.print("No");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Invalid Entry");
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
    }//GEN-LAST:event_jBttnEditActionPerformed

    private void jBttnDlteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDlteActionPerformed
        try {
            String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS", 1);
            if (str == null) {
                System.exit(0);
            }
            String empid = str;
            System.out.print(empid);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("delete from qualdetails where empid='" + empid + "'");
            if(committed>=1)
            {
                System.out.print("Executed");
            }else
            {
                System.out.print("No");
            }
            JOptionPane.showMessageDialog(rootPane,"Deleted");
            jEmpid.setText("");
            jCombqual.setSelectedItem(1);
            jBdUnvst.setText("");
            jInst.setText("");
            jPs.setText("");
            jSpArea.setText("");//GEN-LAST:event_jBttnDlteActionPerformed
            jPercnt.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(empQualification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            private void jEmpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpidActionPerformed
               
            }//GEN-LAST:event_jEmpidActionPerformed

            private void jEmpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmpidKeyPressed
               perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jEmpid, evt,num2);
            }//GEN-LAST:event_jEmpidKeyPressed

            private void jBdUnvstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBdUnvstKeyPressed
               perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jBdUnvst, evt,num1);
            }//GEN-LAST:event_jBdUnvstKeyPressed

            private void jInstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jInstKeyPressed
               perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jInst, evt,num1);
            }//GEN-LAST:event_jInstKeyPressed

            private void jPsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPsKeyPressed
               
            }//GEN-LAST:event_jPsKeyPressed

            private void jSpAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpAreaKeyPressed
                perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jSpArea, evt,num1);
            }//GEN-LAST:event_jSpAreaKeyPressed

            private void jPercntKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPercntKeyPressed
              perform1 p1=new perform1();
                 String num1="Alpha";
                 String num2="Numeric";
                String num3="Alphanumeric";
                 p1.dis(jPercnt, evt,num2);
            }//GEN-LAST:event_jPercntKeyPressed
    public static boolean  isValidEmp(String empId) throws SQLException{  
            boolean isExist = false; 
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql= "select * from empdetails where empid='"+empId+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                isExist = true;
            }
            return isExist;  
      }            
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBdUnvst;
    private javax.swing.JButton jBttnAdd;
    private javax.swing.JButton jBttnDlte;
    private javax.swing.JButton jBttnEdit;
    private javax.swing.JButton jBttnSrch;
    private javax.swing.JComboBox jCombqual;
    private javax.swing.JTextField jEmpid;
    private javax.swing.JTextField jInst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPercnt;
    private javax.swing.JTextField jPs;
    private javax.swing.JTextField jSpArea;
    // End of variables declaration//GEN-END:variables
    
}
