/*
 * empSalary.java
 *
 * Created on March 31, 2014, 3:27 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class empSalary extends javax.swing.JInternalFrame {
    
    /** Creates new form empSalary */
    public empSalary() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jEmpid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jnam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCombdc = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jdnam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jHra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jNs = new javax.swing.JTextField();
        jBttnAdd = new javax.swing.JButton();
        jBttnEdit = new javax.swing.JButton();
        jBttnSrch = new javax.swing.JButton();
        jBttnDlte = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("SALARY  DETAILS");

        jLabel2.setText("EMPLOYEE ID");

        jEmpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpidActionPerformed(evt);
            }
        });
        jEmpid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmpidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jEmpidKeyTyped(evt);
            }
        });

        jLabel3.setText("EMPLOYEE NAME");

        jnam.setEditable(false);

        jLabel4.setText("DESIGNATION CODE");

        jCombdc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCombdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombdcActionPerformed(evt);
            }
        });

        jLabel5.setText("DESIGNATION NAME");

        jdnam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdnamKeyPressed(evt);
            }
        });

        jLabel6.setText("BASIC PAY");

        jBp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBpKeyPressed(evt);
            }
        });

        jLabel7.setText("DA");

        jDa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDaKeyPressed(evt);
            }
        });

        jLabel8.setText("HRA");

        jHra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jHraKeyPressed(evt);
            }
        });

        jLabel9.setText("TA");

        jTa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTaKeyPressed(evt);
            }
        });

        jLabel10.setText("PF");

        jPf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPfKeyPressed(evt);
            }
        });

        jLabel11.setText("NET SALARY");

        jNs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNsKeyPressed(evt);
            }
        });

        jBttnAdd.setText("Add");
        jBttnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddActionPerformed(evt);
            }
        });

        jBttnEdit.setText("Edit");
        jBttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnEditActionPerformed(evt);
            }
        });

        jBttnSrch.setText("Search");
        jBttnSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSrchActionPerformed(evt);
            }
        });

        jBttnDlte.setText("Delete");
        jBttnDlte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDlteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(234, 234, 234))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(235, 235, 235)))
                                .addGap(0, 0, 0)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jnam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(jdnam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jHra, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTa, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jBttnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBttnDlte))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jCombdc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(139, 139, 139))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBttnAdd)
                        .addGap(39, 39, 39)
                        .addComponent(jBttnSrch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jEmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCombdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jdnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jBp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jHra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnAdd)
                    .addComponent(jBttnSrch)
                    .addComponent(jBttnDlte)
                    .addComponent(jBttnEdit))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddActionPerformed
       try {
           String emid = jEmpid.getText().trim();
           String emnam = jnam.getText().trim();
           String descode =(String) jCombdc.getSelectedItem();
           String desname = jdnam.getText().trim();
           String baspay = jBp.getText().trim();
           String da = jDa.getText().trim();
           String hra = jHra.getText().trim();
           String ta = jTa.getText().trim();
           String pf = jPf.getText().trim();
           String netsal = jNs.getText().trim();
           if((jEmpid.getText().equals(""))||(jdnam.getText().equals("")))
         {
          JOptionPane.showMessageDialog(rootPane,"You must enter values ");   
         }
           else
           {
            System.out.print(emid);
            System.out.print(emnam);
            System.out.print(descode);
            System.out.print(desname);
            System.out.print(baspay);
            System.out.print(da);
            System.out.print(hra);
            System.out.print(ta);
            System.out.print(pf);
            System.out.print(netsal);
           java.sql.Statement st = new Main().hrmsDatabase().createStatement();
           int committed = st.executeUpdate("insert into salarydetails(empid,empnam,descode,desnam,baspay,da,hra,ta,pf,netsal)values('" + emid + "','"+emnam+"','"+descode+"','"+desname+"','"+baspay+"','"+da+"','"+hra+"','"+ta+"','"+pf+"','"+netsal+"')");                                   
           if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
        }
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
    }//GEN-LAST:event_jBttnAddActionPerformed

    private void jEmpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpidActionPerformed
       
    }//GEN-LAST:event_jEmpidActionPerformed

    private void jBttnSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSrchActionPerformed
      String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String empid = str;
         System.out.print(empid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from salarydetails where empid='"+empid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jEmpid.setText(rs.getString(1));
                jEmpid.disable();
                jnam.setText(rs.getString(2));
                jCombdc.setSelectedItem(rs.getString(3));
                jdnam.setText(rs.getString(4));
                jBp.setText(rs.getString(5));
                jDa.setText(rs.getString(6));
                jHra.setText(rs.getString(7));
                jTa.setText(rs.getString(8));
                 jPf.setText(rs.getString(9)); 
                   jNs.setText(rs.getString(10));
                
                }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_jBttnSrchActionPerformed

    private void jBttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnEditActionPerformed
         try{
            jEmpid.disable();
            String emid = jEmpid.getText().trim();
            String emnam = jnam.getText().trim();
            String descode =(String) jCombdc.getSelectedItem();
            String desname = jdnam.getText().trim();
            String baspay = jBp.getText().trim();
            String da = jDa.getText().trim();
            String hra = jHra.getText().trim();
              String ta= jTa.getText().trim();
                String pf = jPf.getText().trim();
              String netsal= jNs.getText().trim();
            System.out.print(emid);
            System.out.print(emnam);
            System.out.print(descode);
            System.out.print(desname);
            System.out.print(baspay);
            System.out.print(da);
            System.out.print(hra);
              System.out.print(ta);
                System.out.print(pf);
                 System.out.print(netsal);
             java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("update salarydetails set empnam = '" + emnam + "',descode = '" + descode + "',desnam = '" + desname + "',baspay = '" + baspay+ "',da = '" + da+ "',hra = '" +hra + "',ta = '" +ta + "',pf = '" +pf + "',netsal = '" +netsal+ "'");                                   
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else{
            System.out.print("No");
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
    }//GEN-LAST:event_jBttnEditActionPerformed

    private void jBttnDlteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDlteActionPerformed
        try {
            String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS", 1);
            if (str == null) {
                System.exit(0);
            }
            String emid = str;
            System.out.print(emid);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("delete from salarydetails where empid='" + emid + "'");
            if(committed>=1)
            {
                System.out.print("Executed");
            }else
            {
              System.out.print("No");
            }
            JOptionPane.showMessageDialog(rootPane,"Deleted");
            jEmpid.setText("");
            jnam.setText("");
            jCombdc.setSelectedItem("");
            jdnam.setText("");
            jBp.setText("");
            jDa.setText("");                                         
           jHra.setText("");
            jTa.setText("");
            jPf.setText("");
            jNs.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(empQualification.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_jBttnDlteActionPerformed

    private void jCombdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombdcActionPerformed
    try{
               java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select desnam,baspay from salarydetails where descode='"+(String)jCombdc.getSelectedItem()+"'");
           if(rs.next())
            {
              jdnam.setText(rs.getString("desnam"));
              jBp.setText(rs.getString("baspay"));
            }
            rs.close();
            st.close();

            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
    }//GEN-LAST:event_jCombdcActionPerformed

    private void jEmpidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmpidKeyPressed
        
            perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jEmpid, evt, num2);
            if (evt.getKeyChar()==evt.VK_ENTER){
            try {
            int emid = Integer.parseInt(jEmpid.getText());
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select fname from empdetails where empid = " + emid + "");
            if(rs.next())
            {
             jnam.setText(rs.getString("fname"));
            }
            rs.close();
            st.close();
            } catch (SQLException ex) {                             
            Logger.getLogger(expDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
            /*java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select fname from empdetails where empid = '" + emid + "'");//GEN-LAST:event_jEmpidKeyPressed
            jnam.setText(rs.getString(0));*/
           }

    private void jdnamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdnamKeyPressed
            perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jdnam, evt, num1);
    }//GEN-LAST:event_jdnamKeyPressed

    private void jBpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBpKeyPressed
            perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jBp, evt, num2);
    }//GEN-LAST:event_jBpKeyPressed

    private void jDaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDaKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jDa, evt, num2);
    }//GEN-LAST:event_jDaKeyPressed

    private void jHraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jHraKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jHra, evt, num2);
    }//GEN-LAST:event_jHraKeyPressed

    private void jTaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTaKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jTa, evt, num2);
    }//GEN-LAST:event_jTaKeyPressed

    private void jPfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPfKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jPf, evt, num2);
    }//GEN-LAST:event_jPfKeyPressed

    private void jNsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNsKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jNs, evt, num2);
    }//GEN-LAST:event_jNsKeyPressed

    private void jEmpidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmpidKeyTyped
        /*
        } catch (SQLException ex) {//GEN-LAST:event_jEmpidKeyTyped
        */
    }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empSalary().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jBp;
    private javax.swing.JButton jBttnAdd;
    private javax.swing.JButton jBttnDlte;
    private javax.swing.JButton jBttnEdit;
    private javax.swing.JButton jBttnSrch;
    private javax.swing.JComboBox jCombdc;
    private javax.swing.JTextField jDa;
    private javax.swing.JTextField jEmpid;
    private javax.swing.JTextField jHra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPf;
    private javax.swing.JTextField jTa;
    private javax.swing.JTextField jdnam;
    private javax.swing.JTextField jnam;
    // End of variables declaration//GEN-END:variables
    
}
