/*
 * expDetails.java
 *
 * Created on March 29, 2014, 12:02 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class expDetails extends javax.swing.JInternalFrame {
    
    /** Creates new form expDetails */
    public expDetails() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jeid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCombc = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jpe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jpt = new javax.swing.JTextField();
        jBttnAdd = new javax.swing.JButton();
        jBttnSrch = new javax.swing.JButton();
        jBttnEdit = new javax.swing.JButton();
        jBttndelete = new javax.swing.JButton();
        jComDesig = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("Experience Details");

        jLabel2.setText("Emplyee ID");

        jeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jeidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jeidKeyTyped(evt);
            }
        });

        jLabel3.setText("Emplyee Name");

        jen.setEditable(false);

        jLabel4.setText("Company Name");

        jCombc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INFOSYS", "IBM", "WIPRO", "SATYAM", "TTS" }));

        jLabel5.setText("Place");

        jp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpKeyPressed(evt);
            }
        });

        jLabel6.setText("Designation");

        jd.setEditable(false);
        jd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdKeyPressed(evt);
            }
        });

        jLabel7.setText("Period From");

        jpe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpeKeyPressed(evt);
            }
        });

        jLabel8.setText("Period To");

        jpt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jptKeyPressed(evt);
            }
        });

        jBttnAdd.setText("Add");
        jBttnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnAddActionPerformed(evt);
            }
        });

        jBttnSrch.setText("Search");
        jBttnSrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnSrchActionPerformed(evt);
            }
        });

        jBttnEdit.setText("Edit");
        jBttnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnEditActionPerformed(evt);
            }
        });

        jBttndelete.setText("Delete");
        jBttndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttndeleteActionPerformed(evt);
            }
        });

        jComDesig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jComDesig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComDesigItemStateChanged(evt);
            }
        });

        jLabel9.setText("(yyyy-mm)");

        jLabel10.setText("(yyyy-mm)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBttnAdd)
                                    .addComponent(jLabel8))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBttnSrch)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCombc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jen, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                            .addComponent(jp, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jeid, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jd, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jpt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jpe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(jBttnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                        .addComponent(jBttndelete)
                                        .addGap(58, 58, 58)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComDesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBttnAdd)
                    .addComponent(jBttnSrch)
                    .addComponent(jBttnEdit)
                    .addComponent(jBttndelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnAddActionPerformed
          try {
           String emid = jeid.getText().trim();
           String emnam = jen.getText().trim();
           String comnam =(String) jCombc.getSelectedItem();
           String place = jp.getText().trim();
           String desig = jd.getText().trim();
           String pf = jpe.getText().trim();
           String pt = jpt.getText().trim();
           if((jeid.getText().equals(""))||(jen.getText().equals(""))||(jp.getText().equals(""))||(jd.getText().equals(""))||(jpe.getText().equals(""))||(jpt.getText().equals("")))
           {
          JOptionPane.showMessageDialog(rootPane,"You must enter values ");   
           }
           else {
             System.out.print(emid);
            System.out.print(emnam);
            System.out.print(comnam);
            System.out.print(place);
            System.out.print(desig);
            System.out.print(pf);
            System.out.print(pt);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
           int committed = st.executeUpdate("insert into expdetails(empid,empnam,com,pla,des,pf,pt)values('" + emid + "','"+emnam+"','"+comnam+"','"+place+"','"+desig+"','"+pf+"','"+pt+"')");                                   
           if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
        }
           }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
          
    }//GEN-LAST:event_jBttnAddActionPerformed

    private void jBttnSrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnSrchActionPerformed
        String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String empid = str;
         System.out.print(empid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from expdetails where empid='"+empid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jeid.setText(rs.getString(1));
                jeid.disable();
                jen.setText(rs.getString(2));
                jCombc.setSelectedItem(rs.getString(3));
                jp.setText(rs.getString(4));
                jd.setText(rs.getString(5));
                jpe.setText(rs.getString(6));
                jpt.setText(rs.getString(7));
                 }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_jBttnSrchActionPerformed

    private void jBttnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnEditActionPerformed
     try { 
           jeid.disable();
           String emid = jeid.getText().trim();
           String emnam = jen.getText().trim();
           String comnam =(String) jCombc.getSelectedItem();
           String place = jp.getText().trim();
           String desig = jd.getText().trim();
           String pf = jpe.getText().trim();
           String pt = jpt.getText().trim();
             System.out.print(emid);
            System.out.print(emnam);
            System.out.print(comnam);
            System.out.print(place);
            System.out.print(desig);
            System.out.print(pf);
            System.out.print(pt);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql="update expdetails set empnam = '"+emnam+"' ,com = '"+comnam+"',pla = '"+place+"',des = '"+desig+"',pf = '"+pf+"',pt = '"+pt+"' where empid = '"+emid+"'";
            int committed = st.executeUpdate(sql);                                
           if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else{
            System.out.print("No");
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }  
    }//GEN-LAST:event_jBttnEditActionPerformed

    private void jBttndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttndeleteActionPerformed
     try {
            String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS", 1);
            if (str == null) {
                System.exit(0);
            }
            String emid = str;
            System.out.print(emid);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("delete from expdetails where empid='" + emid + "'");
            if(committed>=1)
            {
                System.out.print("Executed");
            }else
            {
              System.out.print("No");
            }
            JOptionPane.showMessageDialog(rootPane,"Deleted");
            jeid.setText("");
            jen.setText("");
            jCombc.setSelectedItem("");
            jp.setText("");
            jd.setText("");
            jpe.setText("");                                         
           jpt.setText("");
          } 
     catch (SQLException ex) {
            Logger.getLogger(empQualification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBttndeleteActionPerformed

    private void jeidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeidKeyPressed

           perform1 p1 = new perform1();
           String num1 = "Alpha";
            String num2 = "Numeric";
           String num3 = "Alphanumeric";
           p1.dis(jeid, evt, num2);
            if (evt.getKeyChar()==evt.VK_ENTER){
            try {
            int emid = Integer.parseInt(jeid.getText());
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select fname from empdetails where empid = " + emid + "");
            if(rs.next())
            {
             jen.setText(rs.getString("fname"));
            }
            rs.close();
            st.close();
            
        } catch (SQLException ex) {                             
            Logger.getLogger(expDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
           /* int emid = Integer.parseInt(jeid.getText());
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select fname from empdetails where empid = '" + emid + "'");
            jen.setText(rs.getString(0));
        } catch (SQLException ex) {//GEN-LAST:event_jeidKeyPressed
            Logger.getLogger(expDetails.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    private void jpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpKeyPressed
       perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jeid, evt, num1);
    }//GEN-LAST:event_jpKeyPressed

    private void jeidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeidKeyTyped
        /*
        } catch (SQLException ex) {//GEN-LAST:event_jeidKeyTyped
*/}
private void jdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdKeyPressed

}//GEN-LAST:event_jdKeyPressed

private void jComDesigItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComDesigItemStateChanged
     try
    {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select desname from desdetails where descode='"+(String)jComDesig.getSelectedItem()+"'");
           if(rs.next())
            {
              jd.setText(rs.getString("desname"));      
            }
            rs.close();
            st.close();

            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
}//GEN-LAST:event_jComDesigItemStateChanged

private void jpeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpeKeyPressed
    if (evt.getKeyChar()==evt.VK_ENTER)
         {
              String str=jpe.getText();
              if(isValidDate(str))
        { 
                  //    System.out.println("valid");    
            }   
           else  
           {  
               JOptionPane.showMessageDialog(null,"Invalid Date");
               jpe.setText("");
           }   
         }
}//GEN-LAST:event_jpeKeyPressed

private void jptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jptKeyPressed
    if (evt.getKeyChar()==evt.VK_ENTER)
         {
              String str=jpt.getText();
              if(isValidDate(str))
        { 
                  //    System.out.println("valid");    
            }   
           else  
           {  
               JOptionPane.showMessageDialog(null,"Invalid Date");
               jpt.setText("");
           }   
         }
}//GEN-LAST:event_jptKeyPressed
public static boolean  isValidDate(String date){  
            boolean isValid = false;  
            //String expression = "^[0-1][1-9][- / ]?(0[1-9]|[12][0-9]|3[01])[- /]?(18|19|20|21)\\d{2}$";  
            //String expression = "(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((19|20)\\d\\d)";  
            String expression = "((19|20)\\d\\d)-(0?0[1-9]|1[012])";  
            /* 
            * ^[0-1][1-9] : The month starts with a 0 and a digit between 1 and 9 
            * [- / ]?: Followed by  an optional "-" or "/". 
          * (0[1-9]|[12][0-9]|3[01]) : The day part must be either between 01-09, or 10-29 or 30-31. 
          * [- / ]?: Day part will be followed by  an optional "-" or "/". 
          * (18|19|20|21)\\d{2}$ : Year begins with either 18, 19, 20 or 21 and ends with two digits. 
          */  
          CharSequence inputStr = date;  
          Pattern pattern = Pattern.compile(expression,Pattern.CASE_INSENSITIVE);  
          Matcher matcher = pattern.matcher(inputStr);  
          if(matcher.matches()){  
              isValid = true;  
          }  
          return isValid;  
      }   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnAdd;
    private javax.swing.JButton jBttnEdit;
    private javax.swing.JButton jBttnSrch;
    private javax.swing.JButton jBttndelete;
    private javax.swing.JComboBox jComDesig;
    private javax.swing.JComboBox jCombc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jd;
    private javax.swing.JTextField jeid;
    private javax.swing.JTextField jen;
    private javax.swing.JTextField jp;
    private javax.swing.JTextField jpe;
    private javax.swing.JTextField jpt;
    // End of variables declaration//GEN-END:variables
    
}
