/*
 * NewJInternalFrame.java
 *
 * Created on March 27, 2014, 4:45 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class frmEmpCmpnstn extends javax.swing.JInternalFrame {
    
    /** Creates new form NewJInternalFrame */
    public frmEmpCmpnstn() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jei = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jsr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jin = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        srch = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setText("COMPENSATION DETAILS");

        jei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jeiKeyPressed(evt);
            }
        });

        jLabel2.setText("EMPLOYEE ID");

        jsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsrKeyPressed(evt);
            }
        });

        jLabel3.setText("SALARY RANGE");

        jLabel4.setText("ANNUAL INCOME");

        jai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jaiKeyPressed(evt);
            }
        });

        jLabel5.setText("TAX");

        jT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTKeyPressed(evt);
            }
        });

        jLabel6.setText("LOAN");

        jl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlKeyPressed(evt);
            }
        });

        jLabel7.setText("FACILITIES");

        jf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jfKeyPressed(evt);
            }
        });

        jLabel8.setText("INSURANCE");

        jin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jinKeyPressed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        srch.setText("Search");
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(46, 46, 46)
                        .addComponent(srch)
                        .addGap(50, 50, 50)
                        .addComponent(edit)
                        .addGap(156, 156, 156))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addContainerGap())
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3))
                                            .addGap(67, 67, 67)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jsr)
                                                .addComponent(jei)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6))
                                            .addGap(75, 75, 75)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jT, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jai)
                                                .addComponent(jl, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jf)
                                                .addComponent(jin)
                                                .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGap(50, 50, 50)))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(srch)
                    .addComponent(edit)
                    .addComponent(delete))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     try {
           String emid = jei.getText().trim();
           String salra = jsr.getText().trim();
           String anin = jai.getText();
           String tax = jT.getText().trim();
           String loan = jl.getText().trim();
           String fac = jf.getText().trim();
           String insu = jin.getText().trim();
           if(jei.getText().equals("")||jsr.getText().equals("")||jai.getText().equals("")||jT.getText().equals("")||jl.getText().equals("")||jf.getText().equals("")||jin.getText().equals("")) {
               JOptionPane.showMessageDialog(rootPane,"You must enter values ");
           }
           else {
            System.out.print(emid);
            System.out.print(salra);
            System.out.print(anin);
            System.out.print(tax);
            System.out.print(loan);
            System.out.print(fac);
            System.out.print(insu);
            boolean isExist = isValidEmp(emid);
        if(isExist){
           java.sql.Statement st = new Main().hrmsDatabase().createStatement();
           int committed = st.executeUpdate("insert into compdetails(emid,salra,anin,tax,loan,fac,insu)values('" + emid + "','"+salra+"','"+anin+"','"+tax+"','"+loan+"','"+fac+"','"+insu+"')");                                   
                if(committed>=1)
                    {
                    System.out.print("Executed");
                    JOptionPane.showMessageDialog(rootPane,"Saved!");
                     }
                 else{
                      System.out.print("No");
                     }
                 }
         else{
               JOptionPane.showMessageDialog(rootPane,"Invalid Entry!"); 
            }
           }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
    }//GEN-LAST:event_addActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
       String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String emid = str;
         System.out.print(emid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from compdetails where emid='"+emid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jei.setText(rs.getString(1));
                jei.disable();
                jsr.setText(rs.getString(2));
                jai.setText(rs.getString(3));
                jT.setText(rs.getString(4));
                jl.setText(rs.getString(5));
                jf.setText(rs.getString(6));
                jin.setText(rs.getString(7));
                 }
             else {
                System.out.print("No");
             }
                 }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_srchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
     try {
             jei.disable();
           String emid = jei.getText().trim();
           String salra = jsr.getText().trim();
           String anin = jai.getText();
           String tax = jT.getText().trim();
           String loan = jl.getText().trim();
           String fac = jf.getText().trim();
           String insu = jin.getText().trim();
            System.out.print(emid);
            System.out.print(salra);
            System.out.print(anin);
            System.out.print(tax);
            System.out.print(loan);
            System.out.print(fac);
            System.out.print(insu);
            boolean isExist = isValidEmp(emid);
        if(isExist){
           java.sql.Statement st = new Main().hrmsDatabase().createStatement();
           int committed = st.executeUpdate("update compdetails set salra = '"+salra+"',anin = '"+anin+"',tax = '"+tax+"',loan = '"+loan+"',fac ='"+fac+"',insu = '"+insu+"'");                                   
           if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else{
            System.out.print("No");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Invalid Entry!"); 
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }   
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try {
            String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS", 1);
            if (str == null) {
                System.exit(0);
            }
            String emid = str;
            System.out.print(emid);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("delete from compdetails where emid='" + emid + "'");
            if(committed>=1)
            {
                System.out.print("Executed");
            }else
            {
              System.out.print("No");
            }
            JOptionPane.showMessageDialog(rootPane,"Deleted");
            jei.setText("");
            jsr.setText("");
            jai.setText("");
            jT.setText("");
            jl.setText("");                                         
           jf.setText("");
            jin.setText("");
           } 
        catch (SQLException ex) {
            Logger.getLogger(empQualification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jeiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeiKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jei, evt, num2);
            
    }//GEN-LAST:event_jeiKeyPressed

    private void jsrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsrKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jsr, evt, num2);
    }//GEN-LAST:event_jsrKeyPressed

    private void jaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jaiKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jai, evt, num2);
    }//GEN-LAST:event_jaiKeyPressed

    private void jTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jT, evt, num2);
    }//GEN-LAST:event_jTKeyPressed

    private void jlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jl, evt, num2);
            
    }//GEN-LAST:event_jlKeyPressed

    private void jfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jf, evt, num3);
    }//GEN-LAST:event_jfKeyPressed

    private void jinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jinKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jin, evt, num2);
    }//GEN-LAST:event_jinKeyPressed
public static boolean  isValidEmp(String empId) throws SQLException{  
            boolean isExist = false; 
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql= "select * from empdetails where empid='"+empId+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                isExist = true;
            }
            return isExist;  
      }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jT;
    private javax.swing.JTextField jai;
    private javax.swing.JTextField jei;
    private javax.swing.JTextField jf;
    private javax.swing.JTextField jin;
    private javax.swing.JTextField jl;
    private javax.swing.JTextField jsr;
    private javax.swing.JButton srch;
    // End of variables declaration//GEN-END:variables
    
}
