package hrms;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
/*
 * frmEmpReg.java
 *
 * Created on April 16, 2014, 1:20 PM
 */
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;


/**
 *
 * @author  user1
 */
public class frmEmpReg extends javax.swing.JInternalFrame {
    int y,ano;
    /** Creates new form frmEmpReg */
    public frmEmpReg(){
        try {
            initComponents();
            String empid = jempid.getText();
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from empdetails where empid='"+empid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
            if(!rs.next()){
                Calendar cal = new GregorianCalendar();
                int month = cal.get(Calendar.MONTH);
                int mon=month+1;
                int year = cal.get(Calendar.YEAR);
                int day = cal.get(Calendar.DAY_OF_MONTH);
                System.out.println("Current date : " + day + "/" + (month + 1) + "/" + year);
                String dat=year+ "-" +mon+ "-" +day;
                jdoj.setText(dat);
            }
            else{
                jdoj.setText(rs.getString(8));
            }
            try{
                java.sql.Statement st2=new Main().hrmsDatabase().createStatement();
                ResultSet rs2=st.executeQuery("select max(empid) from empdetails");
                if(rs2.next())
                {
                    ano=rs2.getInt(1)+1;
                }
                jempid.setText(String.valueOf(ano));
                rs2.close();
                st2.close();
            }
            catch(Exception e )
            {
                System.out.println(e.getMessage());
                System.out.println("yyy");
            }
            jfname.setFocusable(closable);
        } catch (SQLException ex) {
            Logger.getLogger(frmEmpReg.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jempid = new javax.swing.JTextField();
        jfname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jaddr = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRmale = new javax.swing.JRadioButton();
        jRfemale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jdob = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jdoj = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jdept = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jqua = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        search = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jCmbDepart = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jCmbSec = new javax.swing.JComboBox();
        jTxtSec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtPhone = new javax.swing.JTextField();
        jStaff = new javax.swing.JRadioButton();
        jEmployee = new javax.swing.JRadioButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRATION DETAILS");

        jLabel2.setText("EMPLOYEE ID");

        jempid.setEditable(false);

        jfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jfnameKeyPressed(evt);
            }
        });

        jLabel3.setText("FIRST NAME");

        jlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlnameKeyPressed(evt);
            }
        });

        jLabel4.setText("LAST NAME");

        jaddr.setColumns(20);
        jaddr.setRows(5);
        jaddr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jaddrKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jaddr);

        jLabel5.setText("ADDRESS");

        jLabel6.setText("GENDER");

        buttonGroup1.add(jRmale);
        jRmale.setText("MALE");

        buttonGroup1.add(jRfemale);
        jRfemale.setText("FEMALE");

        jLabel7.setText("D.O.B");

        jdob.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jdobCaretUpdate(evt);
            }
        });
        jdob.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jdobComponentAdded(evt);
            }
        });
        jdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jdobFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setText("( yyyy-mm-dd )");

        jLabel12.setText("AGE");

        jage.setEditable(false);

        jLabel10.setText("DATE OF JOINING");

        jdoj.setEditable(false);

        jLabel11.setText("DEPARTMENT");

        jdept.setEditable(false);

        jLabel9.setText("QUALIFICATION");

        jqua.setColumns(20);
        jqua.setRows(5);
        jScrollPane1.setViewportView(jqua);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jCmbDepart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCmbDepart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbDepartItemStateChanged(evt);
            }
        });

        jLabel8.setText("SECTION");

        jCmbSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S1", "S2", "S3", "S4", "S5" }));
        jCmbSec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbSecItemStateChanged(evt);
            }
        });

        jTxtSec.setEditable(false);

        jLabel15.setText("MOBILE NUMBER");

        jTxtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPhoneKeyPressed(evt);
            }
        });

        buttonGroup2.add(jStaff);
        jStaff.setText("Office Staff");

        buttonGroup2.add(jEmployee);
        jEmployee.setText("Labour");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(405, 405, 405))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(add))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jfname)
                                        .addComponent(jempid)
                                        .addComponent(jlname)
                                        .addComponent(jScrollPane2)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jdob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                                        .addComponent(jdoj, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel13))
                                                .addComponent(jRmale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRfemale)))
                                    .addGap(6, 6, 6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCmbDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(jdept))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(134, 134, 134)
                                    .addComponent(edit)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(delete))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jCmbSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(jTxtSec))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(search, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jStaff)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jEmployee)
                                    .addGap(80, 80, 80)))
                            .addGap(84, 84, 84)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRmale)
                            .addComponent(jRfemale))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jdoj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployee)
                    .addComponent(jStaff))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jCmbDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCmbSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search)
                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete)
                    .addComponent(add))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if ((jempid.getText().equals("")) || (jfname.getText().equals("")) || (jlname.getText().equals("")) || (jaddr.getText().equals("")) || (jdob.getText().equals("")) || (jage.getText().equals("")) || (jdoj.getText().equals("")) || (jqua.getText().equals(""))||(jTxtPhone.getText().equals(""))) {
            JOptionPane.showMessageDialog(rootPane, "You must enter values ");
        } else {
            try {
                int empid = Integer.parseInt(jempid.getText().trim());
                String empfname = jfname.getText().trim();
                String emplname = jlname.getText().trim();
                String Addr = jaddr.getText();
                String gen = null;
                if (jRmale.isSelected()) {
                    gen = "Male";
                }
                if (jRfemale.isSelected()) {
                    gen = "Female";
                }
                String dob = jdob.getText().trim();
                int age = Integer.parseInt(jage.getText().trim());
                String doj = jdoj.getText().trim();
                int depCod = Integer.parseInt(jCmbDepart.getSelectedItem().toString());
                String secCod = jCmbSec.getSelectedItem().toString().trim();
                String qual = jqua.getText();
                String phone = jTxtPhone.getText();
                int len = phone.length();
                Character first = Character.valueOf(phone.charAt(0));
                if(len==10&&((first == '9') || (first == '8')||(first=='7')))
                {
                    validateDob(jdob.getText());
                    java.sql.Statement st = new Main().hrmsDatabase().createStatement();
                    int committed = st.executeUpdate("insert into empdetails(empid,fname,lname,addr,gender,dob,age,doj,dept,section,qual,phone) values(" + empid + ",'" + empfname + "','" + emplname + "','" + Addr + "','" + gen + "','" + dob + "','" + age + "','" + doj + "','" + depCod + "','" + secCod + "','" + qual + "','"+phone+"')");
                    if (committed >= 1) {
                        System.out.print("Executed");
                        JOptionPane.showMessageDialog(rootPane, "Saved!");
                        jdob.disable();
                    } else {
                        System.out.print("No");
                         JOptionPane.showMessageDialog(rootPane, "Employee Already Exist!");
                    }
                    }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Phone Number");
                    jTxtPhone.setText("");
                    
                }
            if(jStaff.isSelected()){
                java.sql.Statement st2 = new Main().hrmsDatabase().createStatement();
                    int committed2 = st2.executeUpdate("insert into login(uname,pass) values(" + empid + ",'"+phone+"')");
                    if (committed2 >= 1) {
                        System.out.print("Staff Registration");
                                         } 
                    else {
                        System.out.print("Registration Failed!");
                    }
            }
            }catch (SQLException ex) {
                Logger.getLogger(frmEmpReg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         
}//GEN-LAST:event_addActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
      String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "EMPLOYEE SEARCH",1);
        if(str==null)
		System.exit(0);
       String empid = str;
         System.out.print(empid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from empdetails where empid='"+empid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jempid.setText(rs.getString(1));
                jempid.disable();
                jdob.disable();
                jfname.setText(rs.getString(2));
                jlname.setText(rs.getString(3));
                jaddr.setText(rs.getString(4));
                 if ("Male".equals(rs.getString(5))) {
                    jRmale.doClick();
                }
                else {
                    jRfemale.doClick();
                }
                
                jdob.setText(rs.getString(6));
                jage.setText(rs.getString(7));
                jdoj.setText(rs.getString(8));
                jCmbDepart.setSelectedItem(rs.getString(9)); 
                jCmbSec.setSelectedItem(rs.getString(10)); 
                 jqua.setText(rs.getString(11));
                 jTxtPhone.setText(rs.getString(12));
                }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
    }//GEN-LAST:event_searchActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
      try {
            int empid = Integer.parseInt(jempid.getText().trim());
            jempid.disable();
            jdoj.disable();
            String empfname = jfname.getText().trim();
            String emplname = jlname.getText().trim();
            String Addr = jaddr.getText();
            String gen=null;
            if (jRmale.isSelected()) {
                gen = "Male";
            }
            if (jRfemale.isSelected()) {
                gen = "Female";
            }
            String dob = jdob.getText().trim();
            int age = Integer.parseInt(jage.getText().trim());
            String doj = jdoj.getText().trim();
            String depart = jCmbDepart.getSelectedItem().toString();
            String sect = jCmbSec.getSelectedItem().toString();
            String qual = jqua.getText();
            String phone = jTxtPhone.getText();
            int len = phone.length();
        if(len==10)
        { 
           System.out.print(jempid);
           System.out.print(jfname);
           System.out.print(jlname);
           System.out.print(Addr);
            System.out.print(gen);
           System.out.print(dob);
           System.out.print(age);
           System.out.print(doj);
            System.out.print(depart);
            System.out.print(sect);
            System.out.print(qual);
         java.sql.Statement st = new Main().hrmsDatabase().createStatement();
     int committed = st.executeUpdate("update empdetails set fname = '"+empfname+"',lname = '"+emplname+"',addr = '"+Addr+"',gender = '"+gen+"',dob = '"+dob+"',age = '"+age+"',doj = '"+doj+"',dept = '"+depart+"',dept = '"+depart+"',qual = '"+qual+"',phone = '"+phone+"' where empid = '"+empid+"'");
        if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else
        {
         System.out.print("NO");
        }
            
       }
             else  
           {  
               JOptionPane.showMessageDialog(null,"Invalid Phone Number");
               jTxtPhone.setText("");
               
           }
      }
       catch(Exception e)
       {
           System.out.print(e.getMessage());
           System.out.print("yyy");
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       
   }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
         if(str==null)
		System.exit(0);
         String empid = str;
         System.out.print(empid);
        try
        {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            int committed1 = st.executeUpdate("delete from empdetails where empid='"+empid+"'");
           if(committed1>=1)
            {
                System.out.print("Executed");
            }else
            {
                System.out.print("No");
            }
           JOptionPane.showMessageDialog(rootPane,"Deleted");
        
        }
        
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
         jempid.setText("");
         jfname.setText("");
         jlname.setText("");
         jaddr.setText("");
         jRmale.setSelected(false);
         jRfemale.setSelected(false);
         jage.setText("");
         jdob.setText("");
         jdoj.setText("");
         jdept.setText("");
         jqua.setText("");
          jTxtPhone.setText("");
    }//GEN-LAST:event_deleteActionPerformed

    private void jfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfnameKeyPressed
        perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jfname, evt,num1);
    }//GEN-LAST:event_jfnameKeyPressed

    private void jlnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlnameKeyPressed
      perform1 p1=new perform1();
         String num1="Alpha";
          p1.dis(jlname, evt,num1);   
    }//GEN-LAST:event_jlnameKeyPressed

    private void jaddrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jaddrKeyPressed
       
    }//GEN-LAST:event_jaddrKeyPressed

    private void jCmbDepartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbDepartItemStateChanged
         try{
      {            
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from depdetails where dcode='"+(String)jCmbDepart.getSelectedItem()+"'");
           if(rs.next())
            {
              jdept.setText(rs.getString("dname"));      
            }
            rs.close();
            st.close();
  }          
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from section where dcode='"+(String)jCmbDepart.getSelectedItem()+"'");
           if(rs.next())
            {
              jCmbSec.setSelectedItem(rs.getString("scode"));      
            }
            rs.close();
            st.close();
            
        } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
    }//GEN-LAST:event_jCmbDepartItemStateChanged

    private void jCmbSecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbSecItemStateChanged
       try{
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select sname from section where scode='"+(String)jCmbSec.getSelectedItem()+"'");
           if(rs.next())
            {
              jTxtSec.setText(rs.getString("sname"));      
            }
            rs.close();
            st.close();
        } catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        } 
    }//GEN-LAST:event_jCmbSecItemStateChanged

    private void jTxtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPhoneKeyPressed
        perform1 p1=new perform1();
         String num1="Alpha";
         String num2="Numeric";
         String num3="Alphanumeric";
        p1.dis(jTxtPhone, evt,num2);
        
    }//GEN-LAST:event_jTxtPhoneKeyPressed

    private void jdobCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jdobCaretUpdate
       validateDob(jdob.getText());
    }//GEN-LAST:event_jdobCaretUpdate

    private void jdobComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jdobComponentAdded
         
    }//GEN-LAST:event_jdobComponentAdded

    private void jdobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jdobFocusLost
        validateDob(jdob.getText());
        if(!(jdob.getText().length()==10)){
              JOptionPane.showMessageDialog(null,"Invalid Date!");
              jdob.setText("");
        }
    }//GEN-LAST:event_jdobFocusLost
     public static boolean  isValidDate(String date){  
          String expression = "((19|20)\\d\\d)-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])";
          String dateFormat = "yyyy-MM-dd";
          CharSequence inputStr = date;  
          Pattern pattern = Pattern.compile(expression);  
          Matcher matcher = pattern.matcher(inputStr);  
          if(matcher.matches()){
          SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
		sdf.setLenient(false);
        	try {
 
			//if not valid, it will throw ParseException
			Date dateValidated = sdf.parse(date);
			System.out.println(dateValidated);
                        return true;
		}
          catch (ParseException e) {
 			e.printStackTrace();
			return false;
		}
          }
          else{
              return false;
          }
		
      }
     public void validateDob(String date){
         if(jdob.getText().length()==10)
         {
             String str=jdob.getText();
             if(isValidDate(str))
              {
             String sub=jdob.getText().substring(0,4).toString();
             String y = jdoj.getText().substring(0,4).toString();
             int ag=Integer.parseInt(y)-Integer.parseInt(sub);
             if(ag>=20&&ag<=35){
             jage.setText(String.valueOf(ag));
             System.out.println("valid");    
              }
             else{
                 jdob.setText("");
                 jage.setText("");
                 JOptionPane.showMessageDialog(null,"Age must be in the range 20-35");
                 }
              }
           else  
           {  
               jdob.setText("");
               jage.setText("");
               JOptionPane.showMessageDialog(null,"Invalid Date");
            }   
         }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JComboBox jCmbDepart;
    private javax.swing.JComboBox jCmbSec;
    private javax.swing.JRadioButton jEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRfemale;
    private javax.swing.JRadioButton jRmale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jStaff;
    private javax.swing.JTextField jTxtPhone;
    private javax.swing.JTextField jTxtSec;
    private javax.swing.JTextArea jaddr;
    private javax.swing.JTextField jage;
    private javax.swing.JTextField jdept;
    private javax.swing.JTextField jdob;
    private javax.swing.JTextField jdoj;
    private javax.swing.JTextField jempid;
    private javax.swing.JTextField jfname;
    private javax.swing.JTextField jlname;
    private javax.swing.JTextArea jqua;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
    
}
