/*
 * frmEMPSkill.java
 *
 * Created on March 21, 2014, 4:56 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class frmEMPSkill extends javax.swing.JInternalFrame {
    
    /** Creates new form frmEMPSkill */
    public frmEMPSkill() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jei = new javax.swing.JTextField();
        jd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        je = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        js = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        ed = new javax.swing.JButton();
        deiete = new javax.swing.JButton();
        jCmbDep = new javax.swing.JComboBox();

        setClosable(true);

        jLabel7.setFont(new java.awt.Font("Calisto MT", 1, 24));
        jLabel7.setText("SKILL  DETAILS");

        jei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jeiKeyPressed(evt);
            }
        });

        jd.setEditable(false);

        jLabel1.setText("Employee ID");

        jLabel2.setText("Department");

        jLabel3.setText("Project Head");

        jp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpKeyPressed(evt);
            }
        });

        jLabel4.setText("Current Hand");

        jc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcKeyPressed(evt);
            }
        });

        jLabel5.setText("Experience");

        je.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jeKeyPressed(evt);
            }
        });

        jLabel6.setText("Skill");

        js.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsKeyPressed(evt);
            }
        });

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        ed.setText("Edit");
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });

        deiete.setText("Delete");
        deiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deieteActionPerformed(evt);
            }
        });

        jCmbDep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jCmbDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbDepItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(je, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jc, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jei, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jp, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jd, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(ed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(deiete)
                        .addGap(39, 39, 39)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(add)
                .addGap(43, 43, 43)
                .addComponent(Search)
                .addContainerGap(242, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(je, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(js, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(Search)
                    .addComponent(ed)
                    .addComponent(deiete))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
   String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS",1);
        if(str==null)
		System.exit(0);
       String emid = str;
         System.out.print(emid);
         try
            {
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            String sql="select * from skilldetails where emid='"+emid+"'";
            System.out.print(sql);
            ResultSet rs=st.executeQuery(sql);
             if(rs.next())
                {
                System.out.print("Executed");
                jei.setText(rs.getString(1));
                jei.disable();
                jd.setText(rs.getString(2));
               jp.setText(rs.getString(4));
                jc.setText(rs.getString(5));
                je.setText(rs.getString(6));
                js.setText(rs.getString(7));
                }
             else {
                System.out.print("No");
              }
            }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
             JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
}//GEN-LAST:event_SearchActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
     try {
           String emid = jei.getText().trim();
           String dep = jd.getText().trim();
           String ph = jp.getText().trim();
           String ch = jc.getText().trim();
           String ex= je.getText().trim();
           String sk = js.getText().trim();
           if(jei.getText().equals("")||jd.getText().equals("")||jp.getText().equals("")||jc.getText().equals("")||je.getText().equals("")||js.getText().equals("")) {
               JOptionPane.showMessageDialog(rootPane,"You must enter values ");   
           }
           else {
           System.out.print(emid);
            System.out.print(dep);
            System.out.print(ph);
            System.out.print(ch);
            System.out.print(ex);
            System.out.print(sk);
             boolean isExist = isValidEmp(emid);
        if(isExist){
          java.sql.Statement st = new Main().hrmsDatabase().createStatement();
           int committed = st.executeUpdate("insert into skilldetails(emid,dep,ph,ch,ex,sk)values('" + emid + "','"+dep+"','"+ph+"','"+ch+"','"+ex+"','"+sk+"')");                                   
           if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Saved!");
        }
        else{
            System.out.print("No");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Invalid Entry");
        }
           }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
       }
    }//GEN-LAST:event_addActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
      try {
          jei.disable();
           String emid = jei.getText().trim();
           String dep = jd.getText().trim();
           String ph = jp.getText().trim();
           String ch = jc.getText().trim();
           String ex= je.getText().trim();
           String sk = js.getText().trim();
           System.out.print(emid);
            System.out.print(dep);
            System.out.print(ph);
            System.out.print(ch);
            System.out.print(ex);
            System.out.print(sk);
             boolean isExist = isValidEmp(emid);
        if(isExist){
          java.sql.Statement st = new Main().hrmsDatabase().createStatement();
           int committed = st.executeUpdate("update skilldetails set dep = '"+dep+"',ph = '"+ph+"',ch = '"+ch+"',ex = '"+ex+"',sk = '"+sk+"'");                                   
           if(committed>=1)
        {
            System.out.print("Executed");
            JOptionPane.showMessageDialog(rootPane,"Edited!");
        }
        else{
            System.out.print("No");
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Invalid Entry");
        }
        }
        catch(Exception e)
       {
           System.out.print(e.getMessage());
           JOptionPane.showMessageDialog(rootPane,e.getMessage());
        } 
    }//GEN-LAST:event_edActionPerformed

    private void deieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deieteActionPerformed
         try {
            String str = JOptionPane.showInputDialog(null, "Enter Employee ID : ", "HRMS", 1);
            if (str == null) {
                System.exit(0);
            }
            String emid = str;
            System.out.print(emid);
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            int committed = st.executeUpdate("delete from skilldetails where emid='" + emid + "'");
            if(committed>=1)
            {
                System.out.print("Executed");
            }else
            {
              System.out.print("No");
            }
            JOptionPane.showMessageDialog(rootPane,"Deleted");
            jei.setText("");
            jd.setText("");
            jp.setText("");
            jc.setText("");
            je.setText("");                                         
           js.setText("");
            } 
         catch (SQLException ex) {
            Logger.getLogger(empQualification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deieteActionPerformed

    private void jeiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeiKeyPressed
       perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jei, evt, num2);
    }//GEN-LAST:event_jeiKeyPressed

    private void jCmbDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbDepItemStateChanged
         try{
      {            
            java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs=st.executeQuery("select * from depdetails where dcode='"+(String)jCmbDep.getSelectedItem()+"'");
           if(rs.next())
            {
              jd.setText(rs.getString("dname"));      
            }
            rs.close();
            st.close();
  }          
            } 
        catch(Exception e)
        {
            System.out.print(e.getMessage());
             System.out.print("yyy");
        }
    }//GEN-LAST:event_jCmbDepItemStateChanged

    private void jpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jp, evt, num1);
    }//GEN-LAST:event_jpKeyPressed

    private void jcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(jc, evt, num1);
    }//GEN-LAST:event_jcKeyPressed

    private void jeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jeKeyPressed
            perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(je, evt, num3);
    }//GEN-LAST:event_jeKeyPressed

    private void jsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsKeyPressed
        perform1 p1 = new perform1();
            String num1 = "Alpha";
            String num2 = "Numeric";
            String num3 = "Alphanumeric";
            p1.dis(js, evt, num3);
    }//GEN-LAST:event_jsKeyPressed
  public static boolean  isValidEmp(String empId) throws SQLException{  
            boolean isExist = false; 
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql= "select * from empdetails where empid='"+empId+"'";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                isExist = true;
            }
            return isExist;  
      }      
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton add;
    private javax.swing.JButton deiete;
    private javax.swing.JButton ed;
    private javax.swing.JComboBox jCmbDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jc;
    private javax.swing.JTextField jd;
    private javax.swing.JTextField je;
    private javax.swing.JTextField jei;
    private javax.swing.JTextField jp;
    private javax.swing.JTextField js;
    // End of variables declaration//GEN-END:variables
    
}
