/*
 * logPage.java
 *
 * Created on May 6, 2014, 5:23 PM
 */

package hrms;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author  user1
 */
public class logPage extends javax.swing.JFrame {
    /** Creates new form Login */
    SplashScreen FormSplash = new SplashScreen();
    Thread ThFormSplash = new Thread(FormSplash);
    int f;

    /** Creates new form logPage */
    public logPage() {
        initComponents();
        loadSplashScreen();
        FormSplash.dispose();
        Image icon = Toolkit.getDefaultToolkit().getImage("images/i16x16/users rec.png");
        setIconImage(icon);
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(500, 350);
        setResizable(false);
        setLocation((screen.width - 500) / 2, ((screen.height - 350) / 2));
        setLayout(new BorderLayout());
        JLabel background = new JLabel(new ImageIcon("images/login.jpg"));
        //background.setSize(500, 300);
        add(background);
        //background.setLayout(new FlowLayout());
        
       
    }
    /* This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jBttnLogin = new javax.swing.JButton();
        jTextPasswrd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel2.setText("UserName");

        Password.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        Password.setText("Password");

        jBttnLogin.setText("Login");
        jBttnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnLoginActionPerformed(evt);
            }
        });
        jBttnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBttnLoginKeyPressed(evt);
            }
        });

        jTextPasswrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPasswrdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextPasswrd)
                    .addComponent(jTextUser, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jBttnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(jTextPasswrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jBttnLogin)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnLoginActionPerformed
        String un = jTextUser.getText();
        String pa = jTextPasswrd.getText();
       // System.out.println(un);
    
                // System.out.println(pa);

        try
        {
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql = "select uname,pass from login where uname='" + un + "' and pass='" + pa + "'";
           // System.out.print(sql);
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) 
            {

                 if (pa.equals(rs.getString(2))) 
                 {
                    dispose();
                    //System.out.print("pppp");
                    menuHrms x = new menuHrms(jTextUser.getText());
                    x.setVisible(true);
                }
                 else 
                 {
                  JOptionPane.showMessageDialog(rootPane, "Invalid Login ID and Password ");
                 }

            } 
            else 
            {
                f = 0;
                jTextUser.requestDefaultFocus();
                jTextUser.setText("");
                jTextPasswrd.requestDefaultFocus();
                jTextPasswrd.setText("");
                JOptionPane.showMessageDialog(rootPane, "Invalid Login ID and Password ");

            }


        } catch (Exception e) {
            System.out.print("No connection");
           
        }
    }//GEN-LAST:event_jBttnLoginActionPerformed

    private void jTextPasswrdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPasswrdKeyPressed
         if (evt.getKeyChar()==evt.VK_ENTER){
         String un = jTextUser.getText();
         String pa = jTextPasswrd.getText();
       // System.out.println(un);
    
                // System.out.println(pa);

        try
        {
            java.sql.Statement st = new Main().hrmsDatabase().createStatement();
            String sql = "select uname,pass from login where uname='" + un + "' and pass='" + pa + "'";
           // System.out.print(sql);
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) 
            {

                 if (pa.equals(rs.getString(2))) 
                 {
                    dispose();
                    //System.out.print("pppp");
                    menuHrms x = new menuHrms(jTextUser.getText());
                    x.setVisible(true);
                }
                 else 
                 {
                  JOptionPane.showMessageDialog(rootPane, "Invalid Login ID and Password ");
                 }

            } 
            else 
            {
                f = 0;
                jTextUser.requestDefaultFocus();
                jTextUser.setText("");
                jTextPasswrd.requestDefaultFocus();
                jTextPasswrd.setText("");
                JOptionPane.showMessageDialog(rootPane, "Invalid Login ID and Password ");

            }


        } catch (Exception e) {
            System.out.print(e.getMessage());
           
        } 
        }
    }//GEN-LAST:event_jTextPasswrdKeyPressed

    private void jBttnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBttnLoginKeyPressed
        
    }//GEN-LAST:event_jBttnLoginKeyPressed
     public void loadSplashScreen() {
        //Start the thread
        ThFormSplash.start();
        while (!FormSplash.isShowing()) {
            try {
                //Display the FormSplash for 3 seconds
                Thread.sleep(3000);
            } catch (InterruptedException e) {
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logPage().setVisible(true);
                }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    public javax.swing.JButton jBttnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jTextPasswrd;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables
    
}
