package hrms;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;

/**
 *
 * @author  user1
 */
public class menuHrms extends javax.swing.JFrame {
    
    /** Creates new form MDI */
     Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
  
     SplashScreen FormSplash	 = new SplashScreen(); 
     Thread ThFormSplash = new Thread(FormSplash);
     String xx;
    public menuHrms(String x) {
        initComponents();
        xx=x;
        try {
        UIManager.setLookAndFeel(
        UIManager.getSystemLookAndFeelClassName());
             }
        catch (Exception e) {}
        JFrame.setDefaultLookAndFeelDecorated(true);
        if(!x.equals("admin"))
        {
         System.out.println("xxx");   
         jMenuRegister.setEnabled(false);
         jMenuDepEntry.setEnabled(false);
         jMenuDesigEntry.setEnabled(false);
         jMenuExpDet.setEnabled(false);
         jMenuCompDet.setEnabled(false);
         jMenuSalEntry.setEnabled(false);
         jMenuPlaceDet.setEnabled(false);
         
        }
        setLocation(0,0);
    
	setSize(screen);
		
	
    } 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuRegister = new javax.swing.JMenuItem();
        jMenuExpDet = new javax.swing.JMenuItem();
        jMenuCompDet = new javax.swing.JMenuItem();
        jMenuTrainDet = new javax.swing.JMenuItem();
        jMenuSkillDet = new javax.swing.JMenuItem();
        jMenuQualDet = new javax.swing.JMenuItem();
        jMenuFamDet = new javax.swing.JMenuItem();
        jMenuPlaceDet = new javax.swing.JMenuItem();
        jMenuSalEntry = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuDepEntry = new javax.swing.JMenuItem();
        jMenuDesigEntry = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuRepRegister = new javax.swing.JMenuItem();
        jMenuRepDepart = new javax.swing.JMenuItem();
        jMenuRepDesig = new javax.swing.JMenuItem();
        jMenuRepExp = new javax.swing.JMenuItem();
        jMenuRepQual = new javax.swing.JMenuItem();
        jMenuRepSalary = new javax.swing.JMenuItem();
        jMenuRepFamily = new javax.swing.JMenuItem();
        jMenuRepTrain = new javax.swing.JMenuItem();
        jMenuRepSkill = new javax.swing.JMenuItem();
        jMenuRepCompnstn = new javax.swing.JMenuItem();
        jMenuRepPlcmnt = new javax.swing.JMenuItem();
        chngePass = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar4.add(jMenu11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jDesktopPane1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrms/HRMS_Main.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1404, 700);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        jMenu2.setText("Employee");

        jMenuRegister.setText("Registration");
        jMenuRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegisterActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuRegister);

        jMenuExpDet.setText("Experience Details");
        jMenuExpDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExpDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuExpDet);

        jMenuCompDet.setText("Compensation Details");
        jMenuCompDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCompDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCompDet);

        jMenuTrainDet.setText("Training Details");
        jMenuTrainDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTrainDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuTrainDet);

        jMenuSkillDet.setText("Skill Details");
        jMenuSkillDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSkillDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSkillDet);

        jMenuQualDet.setText("Qualification Details");
        jMenuQualDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQualDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQualDet);

        jMenuFamDet.setText("Family Details");
        jMenuFamDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFamDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuFamDet);

        jMenuPlaceDet.setText("Placement Details");
        jMenuPlaceDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPlaceDetActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPlaceDet);

        jMenuSalEntry.setText("Salary Entry");
        jMenuSalEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalEntryActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSalEntry);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Department");

        jMenuDepEntry.setText("Entry");
        jMenuDepEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDepEntryActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuDepEntry);

        jMenuDesigEntry.setText("Designation Entry");
        jMenuDesigEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDesigEntryActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuDesigEntry);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Report");

        jMenuRepRegister.setText("Registration");
        jMenuRepRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepRegisterActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepRegister);

        jMenuRepDepart.setText("Department");
        jMenuRepDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepDepartActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepDepart);

        jMenuRepDesig.setText("Designation");
        jMenuRepDesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepDesigActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepDesig);

        jMenuRepExp.setText("Experience");
        jMenuRepExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepExpActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepExp);

        jMenuRepQual.setText("Qualification");
        jMenuRepQual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepQualActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepQual);

        jMenuRepSalary.setText("Salary");
        jMenuRepSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepSalaryActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepSalary);

        jMenuRepFamily.setText("Family");
        jMenuRepFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepFamilyActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepFamily);

        jMenuRepTrain.setText("Training");
        jMenuRepTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepTrainActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepTrain);

        jMenuRepSkill.setText("Skill");
        jMenuRepSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepSkillActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepSkill);

        jMenuRepCompnstn.setText("Compensation");
        jMenuRepCompnstn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepCompnstnActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepCompnstn);

        jMenuRepPlcmnt.setText("Placement");
        jMenuRepPlcmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRepPlcmntActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuRepPlcmnt);

        jMenuBar1.add(jMenu7);

        chngePass.setText("Change Password");

        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        chngePass.add(jMenuItem1);

        jMenuBar1.add(chngePass);

        jMenu12.setText("Help");
        jMenu12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu12ActionPerformed(evt);
            }
        });

        jMenuItem23.setText("About");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem23);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegisterActionPerformed
       frmEmpReg empReg = new frmEmpReg();
       jDesktopPane1.add(empReg);
       setPosition(empReg);
       empReg.setVisible(true);
}//GEN-LAST:event_jMenuRegisterActionPerformed

    private void jMenuExpDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExpDetActionPerformed
       expDetails expDet = new expDetails();
       jDesktopPane1.add(expDet);
       setPosition(expDet);
       expDet.setVisible(true);
}//GEN-LAST:event_jMenuExpDetActionPerformed

    private void jMenuCompDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCompDetActionPerformed
       frmEmpCmpnstn cmpstn = new frmEmpCmpnstn();
       jDesktopPane1.add(cmpstn);
       setPosition(cmpstn);
       cmpstn.setVisible(true);
}//GEN-LAST:event_jMenuCompDetActionPerformed

    private void jMenuTrainDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTrainDetActionPerformed
      empTraining emptrn = new empTraining();
      jDesktopPane1.add(emptrn);
      setPosition(emptrn);
      emptrn.setVisible(true);
}//GEN-LAST:event_jMenuTrainDetActionPerformed

    private void jMenuSkillDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSkillDetActionPerformed
       frmEMPSkill emskl = new frmEMPSkill();
       jDesktopPane1.add(emskl);
       setPosition(emskl);
       emskl.setVisible(true);
}//GEN-LAST:event_jMenuSkillDetActionPerformed

    private void jMenuQualDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQualDetActionPerformed
     empQualification emqua=new empQualification();
     jDesktopPane1.add(emqua);
     setPosition(emqua);
     emqua.setVisible(true);
}//GEN-LAST:event_jMenuQualDetActionPerformed

    private void jMenuFamDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFamDetActionPerformed
     empFamily emfam=new empFamily();
     jDesktopPane1.add(emfam);
     setPosition(emfam);
     emfam.setVisible(true);      
}//GEN-LAST:event_jMenuFamDetActionPerformed

    private void jMenuPlaceDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPlaceDetActionPerformed
     empPlacement empla=new empPlacement();
     jDesktopPane1.add(empla);
     setPosition(empla);
     empla.setVisible(true);  
}//GEN-LAST:event_jMenuPlaceDetActionPerformed

    private void jMenuDepEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDepEntryActionPerformed
     DepartmentDetails depDet = new DepartmentDetails();
     jDesktopPane1.add(depDet);
     setPosition(depDet);
     depDet.setVisible(true);
}//GEN-LAST:event_jMenuDepEntryActionPerformed

    private void jMenuDesigEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDesigEntryActionPerformed
        DesignationDetails desDet = new DesignationDetails();
        jDesktopPane1.add(desDet);
        setPosition(desDet);
        desDet.setVisible(true);
}//GEN-LAST:event_jMenuDesigEntryActionPerformed

    private void jMenuSalEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalEntryActionPerformed
      empSalary empSal = new empSalary();
      jDesktopPane1.add(empSal);
      setPosition(empSal);
      empSal.setVisible(true);
}//GEN-LAST:event_jMenuSalEntryActionPerformed

    private void jMenuRepDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepDepartActionPerformed
     repDepartment repDep = new repDepartment();
     jDesktopPane1.add(repDep);
     setPosition(repDep);
     repDep.setVisible(true);
}//GEN-LAST:event_jMenuRepDepartActionPerformed

    private void jMenuRepDesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepDesigActionPerformed
     repDesignation repDes = new repDesignation();
     jDesktopPane1.add(repDes);
     setPosition(repDes);
     repDes.setVisible(true);  
}//GEN-LAST:event_jMenuRepDesigActionPerformed

    private void jMenuRepExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepExpActionPerformed
     repExperience repExp = new repExperience();
     jDesktopPane1.add(repExp);
     setPosition(repExp);
     repExp.setVisible(true); 
}//GEN-LAST:event_jMenuRepExpActionPerformed

    private void jMenuRepQualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepQualActionPerformed
      repQualification repQua = new repQualification();
     jDesktopPane1.add(repQua);
     setPosition(repQua);
     repQua.setVisible(true);   
}//GEN-LAST:event_jMenuRepQualActionPerformed

    private void jMenuRepSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepSalaryActionPerformed
         repSalary repSal = new repSalary();
     jDesktopPane1.add(repSal);
     setPosition(repSal);
     repSal.setVisible(true);
}//GEN-LAST:event_jMenuRepSalaryActionPerformed

    private void jMenuRepFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepFamilyActionPerformed
       repFamily repFam = new repFamily();
     jDesktopPane1.add(repFam);
     setPosition(repFam);
     repFam.setVisible(true);
}//GEN-LAST:event_jMenuRepFamilyActionPerformed

    private void jMenuRepTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepTrainActionPerformed
       trainRep repTra = new trainRep();
     jDesktopPane1.add(repTra);
     setPosition(repTra);
     repTra.setVisible(true);
}//GEN-LAST:event_jMenuRepTrainActionPerformed

    private void jMenuRepSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepSkillActionPerformed
        repSkill repSk = new repSkill();
     jDesktopPane1.add(repSk);
     setPosition(repSk);
     repSk.setVisible(true);
}//GEN-LAST:event_jMenuRepSkillActionPerformed

    private void jMenuRepCompnstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepCompnstnActionPerformed
         repCompensation repCom = new repCompensation();
     jDesktopPane1.add(repCom);
     setPosition(repCom);
     repCom.setVisible(true);
}//GEN-LAST:event_jMenuRepCompnstnActionPerformed

    private void jMenuRepPlcmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepPlcmntActionPerformed
        repPlacement repPla= new repPlacement();
     jDesktopPane1.add(repPla);
     setPosition(repPla);
     repPla.setVisible(true);
}//GEN-LAST:event_jMenuRepPlcmntActionPerformed

    private void jMenuRepRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRepRegisterActionPerformed
         repRegistration repReg = new repRegistration();
     jDesktopPane1.add(repReg);
     setPosition(repReg);
     repReg.setVisible(true);
}//GEN-LAST:event_jMenuRepRegisterActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        aboutHRMS abt = new aboutHRMS();
     jDesktopPane1.add(abt);
     setPosition(abt);
     abt.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenu12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu12ActionPerformed
        
    }//GEN-LAST:event_jMenu12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        changePassword chgePass = new changePassword(xx);
        jDesktopPane1.add(chgePass);
        setPosition(chgePass);
        chgePass.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
 public void setPosition(JInternalFrame tmp){  
           Dimension desk = jDesktopPane1.getSize();
       Dimension intr = tmp.getSize();
       int width = (desk.width-intr.width)/2;
       int height = (desk.height-intr.height-10)/2;
       tmp.setLocation(width, height); 
               }   
    /**
     * @param args the command line arguments
     */
     public void loadSplashScreen(){
		//Start the thread
		ThFormSplash.start();
		while(!FormSplash.isShowing()){
			try{
				//Display the FormSplash for 10 seconds
				Thread.sleep(3000);
			}catch(InterruptedException e){
			}
		}
	}   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu chngePass;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuCompDet;
    private javax.swing.JMenuItem jMenuDepEntry;
    private javax.swing.JMenuItem jMenuDesigEntry;
    private javax.swing.JMenuItem jMenuExpDet;
    private javax.swing.JMenuItem jMenuFamDet;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuPlaceDet;
    private javax.swing.JMenuItem jMenuQualDet;
    private javax.swing.JMenuItem jMenuRegister;
    private javax.swing.JMenuItem jMenuRepCompnstn;
    private javax.swing.JMenuItem jMenuRepDepart;
    private javax.swing.JMenuItem jMenuRepDesig;
    private javax.swing.JMenuItem jMenuRepExp;
    private javax.swing.JMenuItem jMenuRepFamily;
    private javax.swing.JMenuItem jMenuRepPlcmnt;
    private javax.swing.JMenuItem jMenuRepQual;
    private javax.swing.JMenuItem jMenuRepRegister;
    private javax.swing.JMenuItem jMenuRepSalary;
    private javax.swing.JMenuItem jMenuRepSkill;
    private javax.swing.JMenuItem jMenuRepTrain;
    private javax.swing.JMenuItem jMenuSalEntry;
    private javax.swing.JMenuItem jMenuSkillDet;
    private javax.swing.JMenuItem jMenuTrainDet;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
   }
    

    
