/*
 * repDepartment.java
 *
 * Created on April 4, 2014, 12:42 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import javax.swing.JTable;
import java.text.MessageFormat;

/**
 *
 * @author  user1
 */
public class repDepartment extends javax.swing.JInternalFrame {    
    
    /** Creates new form repDepartment */
    public repDepartment() {
        initComponents();
        jTable1.setRowHeight(25);
        try{
        java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select depdetails.dcode,dname,scode,sname from depdetails,section where depdetails.dcode=section.depcode");
            //rs.first();
            TableModel tm=jTable1.getModel();
            System.out.println("a"); 
        //tm.setValueAt(rs.getString(1),0,0);
        //  tm.setValueAt(rs.getString(1),0,1);
            int i=0;
         while(rs.next())
            {
               System.out.println("b"); 
               tm.setValueAt(rs.getString(1),i,0);
               tm.setValueAt(rs.getString(2),i,1);
               tm.setValueAt(rs.getString(3),i,2);
               tm.setValueAt(rs.getString(4),i,3);
                i++;
            }
             
            System.out.println("d");
            System.out.println(i);
            st.close();
            
             
         }     
catch (SQLException ex) {
            Logger.getLogger(repDepartment.class.getName()).log(Level.SEVERE, null, ex);
     }     catch(Exception e)
     {
        System.out.print( e.getMessage());
     }    
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        print = new javax.swing.JButton();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DEPARTMENT CODE", "DEPARTMENT NAME", "SECTION CODE", "SECTION NAME"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue("DEPARTMENT CODE");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("DEPARTMENT NAME");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("SECTION CODE");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("SECTION NAME");

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("REPORT DEPARTMENT");

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(print)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(print)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
          MessageFormat header = new MessageFormat("Page {0,number,integer}");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, null);
        } catch (java.awt.print.PrinterException e) {
            //System.err.format("Cannot print %s%n", e.getMessage());
        	//System.err.format("a","ca",e.getMessage());
        }
       }                                        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repDepartment().setVisible(true);
            }
        });
    }//GEN-LAST:event_printActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}

