/*
 * repDesignation.java
 *
 * Created on April 1, 2014, 11:43 AM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author  user1
 */
public class repDesignation extends javax.swing.JInternalFrame {
    
    /** Creates new form repDesignation */
    public repDesignation() {
        initComponents();
        jTableDesig.setRowHeight(25);
        try{
        java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select descode,desname,pscale,pgrade from desdetails");
            //rs.first();
            TableModel tm=jTableDesig.getModel();
            System.out.println("a"); 
        //tm.setValueAt(rs.getString(1),0,0);
        //  tm.setValueAt(rs.getString(1),0,1);
            int i=0;
         while(rs.next())
            {
               System.out.println("b"); 
               tm.setValueAt(rs.getString(1),i,0);
               tm.setValueAt(rs.getString(2),i,1);
               tm.setValueAt(rs.getString(3),i,2);
               tm.setValueAt(rs.getString(4),i,3);
                i++;
            }
             
            System.out.println("d");
            System.out.println(i);
            st.close();
            
             
         }     
catch (SQLException ex) {
            Logger.getLogger(repDepartment.class.getName()).log(Level.SEVERE, null, ex);
     }     catch(Exception e)
     {
        System.out.print( e.getMessage());
     }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDesig = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBttnPrint = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);

        jTableDesig.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DESIGNATION CODE", "DESIGNATION NAME", "PAY SCALE", "GRADE"
            }
        ));
        jScrollPane1.setViewportView(jTableDesig);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("REPORT DESIGNATION");

        jBttnPrint.setText("Print");
        jBttnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jBttnPrint))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBttnPrint)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBttnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnPrintActionPerformed
        MessageFormat header = new MessageFormat("Page {0,number,integer}");
        try {
            jTableDesig.print(JTable.PrintMode.FIT_WIDTH, header, null);
        } catch (java.awt.print.PrinterException e) {
            //System.err.format("Cannot print %s%n", e.getMessage());
        	//System.err.format("a","ca",e.getMessage());
        }
    }//GEN-LAST:event_jBttnPrintActionPerformed
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repDepartment().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDesig;
    // End of variables declaration//GEN-END:variables
    
}
