/*
 * repSkill.java
 *
 * Created on April 1, 2014, 3:08 PM
 */

package hrms;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author  user1
 */
public class repSkill extends javax.swing.JInternalFrame {
    
    /** Creates new form repSkill */
    public repSkill() {
        initComponents();
        jTableSkill.setRowHeight(25);
        try{
        java.sql.Statement st=new Main().hrmsDatabase().createStatement();
            ResultSet rs = st.executeQuery("select emid,dep,ph,ch,ex,sk from skilldetails");
            //rs.first();
            TableModel tm=jTableSkill.getModel();
            System.out.println("a"); 
        //tm.setValueAt(rs.getString(1),0,0);
        //  tm.setValueAt(rs.getString(1),0,1);
            int i=0;
         while(rs.next())
            {
               System.out.println("b"); 
               tm.setValueAt(rs.getString(1),i,0);
               tm.setValueAt(rs.getString(2),i,1);
               tm.setValueAt(rs.getString(3),i,2);
               tm.setValueAt(rs.getString(4),i,3);
               tm.setValueAt(rs.getString(5),i,4);
               tm.setValueAt(rs.getString(6),i,5);
               i++;
            }
             
            System.out.println("d");
            System.out.println(i);
            st.close();
            
             
         }     
catch (SQLException ex) {
            Logger.getLogger(repDepartment.class.getName()).log(Level.SEVERE, null, ex);
     }     catch(Exception e)
     {
        System.out.print( e.getMessage());
     }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSkill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPrntSkill = new javax.swing.JButton();

        setClosable(true);

        jTableSkill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "EMPLOYEE ID", "DEPARTMENT", "PROJECT HEAD", "CURRENT HAND", "EXPERIENCE", "SKILL"
            }
        ));
        jScrollPane1.setViewportView(jTableSkill);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24));
        jLabel1.setText("REPORT SKILL");

        jPrntSkill.setText("Print");
        jPrntSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrntSkillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jPrntSkill)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPrntSkill)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPrntSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrntSkillActionPerformed
        MessageFormat header = new MessageFormat("Page {0,number,integer}");
        try {
            jTableSkill.print(JTable.PrintMode.FIT_WIDTH, header, null);
        } catch (java.awt.print.PrinterException e) {
            //System.err.format("Cannot print %s%n", e.getMessage());
        	//System.err.format("a","ca",e.getMessage());
        }
    }//GEN-LAST:event_jPrntSkillActionPerformed
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repDepartment().setVisible(true);
            }
        });
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jPrntSkill;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSkill;
    // End of variables declaration//GEN-END:variables
    
}
